/* Generated by tools/gen_game_tables.py from the layout of RFIRE.BIN. Do not edit.
   Collision shapes, graphic descriptors (collision fields only), BNO game fields, shore-water shapes,
   vehicle descriptors (pointer table 0x44afc8), tunables, bunker scripts and the combat tables.
   Addresses, counts and types only: the contents are read from the user's RFIRE.BIN at start-up
   (exe.c, game_tables_load below). */
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include "game.h"
#include "vehicle.h"
#include "weapon.h"
#include "effect.h"
#include "../exe.h"

/* ---- collision shape parts (linked lists, see ShapesOverlap 0x41c800); buffers sized by +0x2c / +0x34 ---- */
static ShapePart shp_444028;
static ShapePart shp_444068;
static ShapePart shp_444450;
static ShapePart shp_444410;
static ShapePart shp_4448a8;
static ShapePart shp_444868;
static ShapePart shp_444af8;
static ShapePart shp_444ab8;
static ShapePart shp_444c90;
static ShapePart shp_444e10;
static ShapePart shp_444e50;
static ShapePart shp_444e90;
static ShapePart shp_447010;
static ShapePart shp_446fd0;
static ShapePart shp_447050;
static ShapePart shp_447090;
static ShapePart shp_44a320;
static ShapePart shp_44a148;
static ShapePart shp_446218;
static ShapePart shp_446030;
static ShapePart shp_445ff0;
static ShapePart shp_446958;
static ShapePart shp_447850;
static ShapePart shp_447890;
static ShapePart shp_448228;
static ShapePart shp_447c78;
static ShapePart shp_448d40;
static ShapePart shp_448db8;
static ShapePart shp_448d7c;
static ShapePart shp_445b04;
static ShapePart shp_445a14;
static ShapePart shp_445ac8;
static ShapePart shp_4459d8;
static ShapePart shp_445b40;
static ShapePart shp_445a50;
static ShapePart shp_445b7c;
static ShapePart shp_445a8c;
static ShapePart shp_442538;
static ShapePart shp_4424f8;
static ShapePart shp_4429b0;
static ShapePart shp_441fe8;
static ShapePart shp_441b08;
static ShapePart shp_448f78;
static ShapePart shp_448f38;
static ShapePart shp_4414b0;
static ShapePart shp_4419e8;
static ShapePart shp_446ac8;
static ShapePart shp_446b50;
static ShapePart shp_446b8c;
static ShapePart shp_446bc8;
static ShapePart shp_446c04;
static ShapePart shp_445360;
static ShapePart shp_44539c;
static ShapePart shp_4453d8;
static ShapePart shp_445414;
static ShapePart shp_449d50;
static ShapePart shp_44cbf0;
static ShapePart shp_44d9a0;
static ShapePart shp_44d100;
static ShapePart shp_44e810;
static ShapePart shp_4431b8;
static ShapePart shp_4494c0;
static ShapePart shp_449438;
static ShapePart shp_4493f8;
static ShapePart shp_455640;
static ShapePart shp_455600;
static ShapePart shp_443330;
static ShapePart shp_4433b8;
static ShapePart shp_443438;
static ShapePart shp_4434b8;
static ShapePart shp_443538;
static int32_t shpv_445b04[8][3];
static uint8_t shpe_445b04[8];
static int32_t shpv_445ac8[8][3];
static uint8_t shpe_445ac8[8];
static int32_t shpv_445b40[8][3];
static uint8_t shpe_445b40[8];
static int32_t shpv_445b7c[8][3];
static uint8_t shpe_445b7c[8];
static int32_t shpv_44cbf0[4][3];
static uint8_t shpe_44cbf0[4];
static int32_t shpv_44d9a0[4][3];
static uint8_t shpe_44d9a0[4];
static int32_t shpv_44d100[4][3];
static uint8_t shpe_44d100[4];
static int32_t shpv_44e810[5][3];
static uint8_t shpe_44e810[5];
static int32_t shpv_4494c0[2][3];
static uint8_t shpe_4494c0[1];
static int32_t shpv_4433b8[6][3];
static uint8_t shpe_4433b8[6];
static int32_t shpv_443438[5][3];
static uint8_t shpe_443438[5];
static int32_t shpv_4434b8[5][3];
static uint8_t shpe_4434b8[5];
static int32_t shpv_443538[5][3];
static uint8_t shpe_443538[5];
typedef struct { ShapePart *s; uint32_t addr; int32_t (*v)[3]; int nv; uint8_t *e; int ne; } ShapeDesc;
static const ShapeDesc shape_descs[71] = {
    { &shp_444028, 0x444028, NULL, 0, NULL, 0 },
    { &shp_444068, 0x444068, NULL, 0, NULL, 0 },
    { &shp_444450, 0x444450, NULL, 0, NULL, 0 },
    { &shp_444410, 0x444410, NULL, 0, NULL, 0 },
    { &shp_4448a8, 0x4448a8, NULL, 0, NULL, 0 },
    { &shp_444868, 0x444868, NULL, 0, NULL, 0 },
    { &shp_444af8, 0x444af8, NULL, 0, NULL, 0 },
    { &shp_444ab8, 0x444ab8, NULL, 0, NULL, 0 },
    { &shp_444c90, 0x444c90, NULL, 0, NULL, 0 },
    { &shp_444e10, 0x444e10, NULL, 0, NULL, 0 },
    { &shp_444e50, 0x444e50, NULL, 0, NULL, 0 },
    { &shp_444e90, 0x444e90, NULL, 0, NULL, 0 },
    { &shp_447010, 0x447010, NULL, 0, NULL, 0 },
    { &shp_446fd0, 0x446fd0, NULL, 0, NULL, 0 },
    { &shp_447050, 0x447050, NULL, 0, NULL, 0 },
    { &shp_447090, 0x447090, NULL, 0, NULL, 0 },
    { &shp_44a320, 0x44a320, NULL, 0, NULL, 0 },
    { &shp_44a148, 0x44a148, NULL, 0, NULL, 0 },
    { &shp_446218, 0x446218, NULL, 0, NULL, 0 },
    { &shp_446030, 0x446030, NULL, 0, NULL, 0 },
    { &shp_445ff0, 0x445ff0, NULL, 0, NULL, 0 },
    { &shp_446958, 0x446958, NULL, 0, NULL, 0 },
    { &shp_447850, 0x447850, NULL, 0, NULL, 0 },
    { &shp_447890, 0x447890, NULL, 0, NULL, 0 },
    { &shp_448228, 0x448228, NULL, 0, NULL, 0 },
    { &shp_447c78, 0x447c78, NULL, 0, NULL, 0 },
    { &shp_448d40, 0x448d40, NULL, 0, NULL, 0 },
    { &shp_448db8, 0x448db8, NULL, 0, NULL, 0 },
    { &shp_448d7c, 0x448d7c, NULL, 0, NULL, 0 },
    { &shp_445b04, 0x445b04, shpv_445b04, 8, shpe_445b04, 8 },
    { &shp_445a14, 0x445a14, NULL, 0, NULL, 0 },
    { &shp_445ac8, 0x445ac8, shpv_445ac8, 8, shpe_445ac8, 8 },
    { &shp_4459d8, 0x4459d8, NULL, 0, NULL, 0 },
    { &shp_445b40, 0x445b40, shpv_445b40, 8, shpe_445b40, 8 },
    { &shp_445a50, 0x445a50, NULL, 0, NULL, 0 },
    { &shp_445b7c, 0x445b7c, shpv_445b7c, 8, shpe_445b7c, 8 },
    { &shp_445a8c, 0x445a8c, NULL, 0, NULL, 0 },
    { &shp_442538, 0x442538, NULL, 0, NULL, 0 },
    { &shp_4424f8, 0x4424f8, NULL, 0, NULL, 0 },
    { &shp_4429b0, 0x4429b0, NULL, 0, NULL, 0 },
    { &shp_441fe8, 0x441fe8, NULL, 0, NULL, 0 },
    { &shp_441b08, 0x441b08, NULL, 0, NULL, 0 },
    { &shp_448f78, 0x448f78, NULL, 0, NULL, 0 },
    { &shp_448f38, 0x448f38, NULL, 0, NULL, 0 },
    { &shp_4414b0, 0x4414b0, NULL, 0, NULL, 0 },
    { &shp_4419e8, 0x4419e8, NULL, 0, NULL, 0 },
    { &shp_446ac8, 0x446ac8, NULL, 0, NULL, 0 },
    { &shp_446b50, 0x446b50, NULL, 0, NULL, 0 },
    { &shp_446b8c, 0x446b8c, NULL, 0, NULL, 0 },
    { &shp_446bc8, 0x446bc8, NULL, 0, NULL, 0 },
    { &shp_446c04, 0x446c04, NULL, 0, NULL, 0 },
    { &shp_445360, 0x445360, NULL, 0, NULL, 0 },
    { &shp_44539c, 0x44539c, NULL, 0, NULL, 0 },
    { &shp_4453d8, 0x4453d8, NULL, 0, NULL, 0 },
    { &shp_445414, 0x445414, NULL, 0, NULL, 0 },
    { &shp_449d50, 0x449d50, NULL, 0, NULL, 0 },
    { &shp_44cbf0, 0x44cbf0, shpv_44cbf0, 4, shpe_44cbf0, 4 },
    { &shp_44d9a0, 0x44d9a0, shpv_44d9a0, 4, shpe_44d9a0, 4 },
    { &shp_44d100, 0x44d100, shpv_44d100, 4, shpe_44d100, 4 },
    { &shp_44e810, 0x44e810, shpv_44e810, 5, shpe_44e810, 5 },
    { &shp_4431b8, 0x4431b8, NULL, 0, NULL, 0 },
    { &shp_4494c0, 0x4494c0, shpv_4494c0, 2, shpe_4494c0, 1 },
    { &shp_449438, 0x449438, NULL, 0, NULL, 0 },
    { &shp_4493f8, 0x4493f8, NULL, 0, NULL, 0 },
    { &shp_455640, 0x455640, NULL, 0, NULL, 0 },
    { &shp_455600, 0x455600, NULL, 0, NULL, 0 },
    { &shp_443330, 0x443330, NULL, 0, NULL, 0 },
    { &shp_4433b8, 0x4433b8, shpv_4433b8, 6, shpe_4433b8, 6 },
    { &shp_443438, 0x443438, shpv_443438, 5, shpe_443438, 5 },
    { &shp_4434b8, 0x4434b8, shpv_4434b8, 5, shpe_4434b8, 5 },
    { &shp_443538, 0x443538, shpv_443538, 5, shpe_443538, 5 },
};
ShapePart *const shape_default_point = &shp_443330;

/* ---- graphic descriptors: only +8 shape, +0xc radius and +0x28 position-adjust hook are used by the sim ---- */
Gfx gfx_4440a8, gfx_4440f0, gfx_444490, gfx_4448e8, gfx_444b38, gfx_444d18;
Gfx gfx_444ed0, gfx_444f18, gfx_444f60, gfx_444fa8, gfx_4470d0, gfx_447118;
Gfx gfx_447160, gfx_44a360, gfx_446258, gfx_446998, gfx_447908, gfx_44794c;
Gfx gfx_447990, gfx_4479d4, gfx_447a18, gfx_447a5c, gfx_447aa0, gfx_447ae4;
Gfx gfx_448268, gfx_4482b0, gfx_448708, gfx_448750, gfx_447d00, gfx_448df8;
Gfx gfx_448e40, gfx_448e88, gfx_445ddc, gfx_445d98, gfx_445e20, gfx_445e64;
Gfx gfx_4428a8, gfx_442d70, gfx_442278, gfx_441d68, gfx_4491c0, gfx_449208;
Gfx gfx_441840, gfx_4418a0, gfx_449318, gfx_448ef0, gfx_441df8, gfx_441db0;
Gfx gfx_441fa0, gfx_442308, gfx_4422c0, gfx_4424b0, gfx_441a78, gfx_441ac0;
Gfx gfx_446b08, gfx_446d28, gfx_449270, gfx_44a3e8, gfx_442e98, gfx_4414f0;
Gfx gfx_445450, gfx_445494, gfx_4454d8, gfx_44551c, gfx_4462c0, gfx_449d90;
Gfx gfx_449dd8, gfx_449fd0, gfx_445fa8, gfx_4455e0, gfx_445624, gfx_445668;
Gfx gfx_4456ac, gfx_447d68, gfx_4471a8, gfx_444588, gfx_444698, gfx_4445d0;
Gfx gfx_444178, gfx_444200, gfx_44b000, gfx_441538, gfx_44cd10, gfx_44cdc0;
Gfx gfx_44ce48, gfx_44cfe0, gfx_44e070, gfx_44e1a8, gfx_44e328, gfx_44e510;
Gfx gfx_44d650, gfx_44d700, gfx_44d788, gfx_44d920, gfx_44ee68, gfx_44eec8;
Gfx gfx_44f298, gfx_4431f8, gfx_4499a0, gfx_449a08, gfx_4495c0, gfx_449628;
Gfx gfx_449730, gfx_449798, gfx_4498a0, gfx_449908, gfx_449aa0, gfx_449ae8;
Gfx gfx_44aa20, gfx_452dc8, gfx_452e0c, gfx_44c668, gfx_44c6b0, gfx_44a610;
Gfx gfx_454f18, gfx_4557f0, gfx_4493b0, gfx_449478, gfx_455680, gfx_455730;
Gfx gfx_43fbb0;
static Gfx *const gfx_descs[121] = { &gfx_4440a8, &gfx_4440f0, &gfx_444490, &gfx_4448e8, &gfx_444b38, &gfx_444d18, &gfx_444ed0, &gfx_444f18, &gfx_444f60, &gfx_444fa8, &gfx_4470d0, &gfx_447118, &gfx_447160, &gfx_44a360, &gfx_446258, &gfx_446998, &gfx_447908, &gfx_44794c, &gfx_447990, &gfx_4479d4, &gfx_447a18, &gfx_447a5c, &gfx_447aa0, &gfx_447ae4, &gfx_448268, &gfx_4482b0, &gfx_448708, &gfx_448750, &gfx_447d00, &gfx_448df8, &gfx_448e40, &gfx_448e88, &gfx_445ddc, &gfx_445d98, &gfx_445e20, &gfx_445e64, &gfx_4428a8, &gfx_442d70, &gfx_442278, &gfx_441d68, &gfx_4491c0, &gfx_449208, &gfx_441840, &gfx_4418a0, &gfx_449318, &gfx_448ef0, &gfx_441df8, &gfx_441db0, &gfx_441fa0, &gfx_442308, &gfx_4422c0, &gfx_4424b0, &gfx_441a78, &gfx_441ac0, &gfx_446b08, &gfx_446d28, &gfx_449270, &gfx_44a3e8, &gfx_442e98, &gfx_4414f0, &gfx_445450, &gfx_445494, &gfx_4454d8, &gfx_44551c, &gfx_4462c0, &gfx_449d90, &gfx_449dd8, &gfx_449fd0, &gfx_445fa8, &gfx_4455e0, &gfx_445624, &gfx_445668, &gfx_4456ac, &gfx_447d68, &gfx_4471a8, &gfx_444588, &gfx_444698, &gfx_4445d0, &gfx_444178, &gfx_444200, &gfx_44b000, &gfx_441538, &gfx_44cd10, &gfx_44cdc0, &gfx_44ce48, &gfx_44cfe0, &gfx_44e070, &gfx_44e1a8, &gfx_44e328, &gfx_44e510, &gfx_44d650, &gfx_44d700, &gfx_44d788, &gfx_44d920, &gfx_44ee68, &gfx_44eec8, &gfx_44f298, &gfx_4431f8, &gfx_4499a0, &gfx_449a08, &gfx_4495c0, &gfx_449628, &gfx_449730, &gfx_449798, &gfx_4498a0, &gfx_449908, &gfx_449aa0, &gfx_449ae8, &gfx_44aa20, &gfx_452dc8, &gfx_452e0c, &gfx_44c668, &gfx_44c6b0, &gfx_44a610, &gfx_454f18, &gfx_4557f0, &gfx_4493b0, &gfx_449478, &gfx_455680, &gfx_455730, &gfx_43fbb0 };
static const uint32_t gfx_addrs[121] = { 0x4440a8, 0x4440f0, 0x444490, 0x4448e8, 0x444b38, 0x444d18, 0x444ed0, 0x444f18, 0x444f60, 0x444fa8, 0x4470d0, 0x447118, 0x447160, 0x44a360, 0x446258, 0x446998, 0x447908, 0x44794c, 0x447990, 0x4479d4, 0x447a18, 0x447a5c, 0x447aa0, 0x447ae4, 0x448268, 0x4482b0, 0x448708, 0x448750, 0x447d00, 0x448df8, 0x448e40, 0x448e88, 0x445ddc, 0x445d98, 0x445e20, 0x445e64, 0x4428a8, 0x442d70, 0x442278, 0x441d68, 0x4491c0, 0x449208, 0x441840, 0x4418a0, 0x449318, 0x448ef0, 0x441df8, 0x441db0, 0x441fa0, 0x442308, 0x4422c0, 0x4424b0, 0x441a78, 0x441ac0, 0x446b08, 0x446d28, 0x449270, 0x44a3e8, 0x442e98, 0x4414f0, 0x445450, 0x445494, 0x4454d8, 0x44551c, 0x4462c0, 0x449d90, 0x449dd8, 0x449fd0, 0x445fa8, 0x4455e0, 0x445624, 0x445668, 0x4456ac, 0x447d68, 0x4471a8, 0x444588, 0x444698, 0x4445d0, 0x444178, 0x444200, 0x44b000, 0x441538, 0x44cd10, 0x44cdc0, 0x44ce48, 0x44cfe0, 0x44e070, 0x44e1a8, 0x44e328, 0x44e510, 0x44d650, 0x44d700, 0x44d788, 0x44d920, 0x44ee68, 0x44eec8, 0x44f298, 0x4431f8, 0x4499a0, 0x449a08, 0x4495c0, 0x449628, 0x449730, 0x449798, 0x4498a0, 0x449908, 0x449aa0, 0x449ae8, 0x44aa20, 0x452dc8, 0x452e0c, 0x44c668, 0x44c6b0, 0x44a610, 0x454f18, 0x4557f0, 0x4493b0, 0x449478, 0x455680, 0x455730, 0x43fbb0 };
/* every graphic above, sorted by address (gfx_by_addr) */
const Gfx *const gfx_table[] = { &gfx_43fbb0, &gfx_4414f0, &gfx_441538, &gfx_441840, &gfx_4418a0, &gfx_441a78, &gfx_441ac0, &gfx_441d68, &gfx_441db0, &gfx_441df8, &gfx_441fa0, &gfx_442278, &gfx_4422c0, &gfx_442308, &gfx_4424b0, &gfx_4428a8, &gfx_442d70, &gfx_442e98, &gfx_4431f8, &gfx_4440a8, &gfx_4440f0, &gfx_444178, &gfx_444200, &gfx_444490, &gfx_444588, &gfx_4445d0, &gfx_444698, &gfx_4448e8, &gfx_444b38, &gfx_444d18, &gfx_444ed0, &gfx_444f18, &gfx_444f60, &gfx_444fa8, &gfx_445450, &gfx_445494, &gfx_4454d8, &gfx_44551c, &gfx_4455e0, &gfx_445624, &gfx_445668, &gfx_4456ac, &gfx_445d98, &gfx_445ddc, &gfx_445e20, &gfx_445e64, &gfx_445fa8, &gfx_446258, &gfx_4462c0, &gfx_446998, &gfx_446b08, &gfx_446d28, &gfx_4470d0, &gfx_447118, &gfx_447160, &gfx_4471a8, &gfx_447908, &gfx_44794c, &gfx_447990, &gfx_4479d4, &gfx_447a18, &gfx_447a5c, &gfx_447aa0, &gfx_447ae4, &gfx_447d00, &gfx_447d68, &gfx_448268, &gfx_4482b0, &gfx_448708, &gfx_448750, &gfx_448df8, &gfx_448e40, &gfx_448e88, &gfx_448ef0, &gfx_4491c0, &gfx_449208, &gfx_449270, &gfx_449318, &gfx_4493b0, &gfx_449478, &gfx_4495c0, &gfx_449628, &gfx_449730, &gfx_449798, &gfx_4498a0, &gfx_449908, &gfx_4499a0, &gfx_449a08, &gfx_449aa0, &gfx_449ae8, &gfx_449d90, &gfx_449dd8, &gfx_449fd0, &gfx_44a360, &gfx_44a3e8, &gfx_44a610, &gfx_44aa20, &gfx_44b000, &gfx_44c668, &gfx_44c6b0, &gfx_44cd10, &gfx_44cdc0, &gfx_44ce48, &gfx_44cfe0, &gfx_44d650, &gfx_44d700, &gfx_44d788, &gfx_44d920, &gfx_44e070, &gfx_44e1a8, &gfx_44e328, &gfx_44e510, &gfx_44ee68, &gfx_44eec8, &gfx_44f298, &gfx_452dc8, &gfx_452e0c, &gfx_454f18, &gfx_455680, &gfx_455730, &gfx_4557f0 };
const int gfx_table_count = 121;

/* ---- static map objects: BNO table 0x451438 (stride 0x38) ---- */
BnoDef bno_defs[BNO_COUNT];
ShoreShape shore_shapes[24];        /* shore tiles 4..23: {invert, rotation (heading>>16), polygon} from 0x443558 */
int32_t shore_boxes[12][4];         /* shore tiles 40..51: land AABB relative to the cell centre (0x443618) */

/* ---- vehicle descriptors (0x44afc8 -> Tank 0x44b3a8, JEEP 0x44b690, MSV 0x44b978, HELI 0x44bc60) ---- */
VehicleDef vehicle_defs[4];

/* Misc tunables. */
int32_t tun_launch_ticks;            /* 0x44b178: tank/MSV forced-forward ticks off the lift */
int32_t tun_idle_drone_ticks;        /* 0x44afa8: same-cell ticks before a Drone is sent */
int32_t tun_door_anim_rate;          /* 0x44afdc */
int32_t tun_heli_takeoff_dx;         /* 0x44b184 */
int32_t tun_heli_turn_up, tun_heli_turn_down; /* 0x44b188 / 0x44b18c */
int32_t tun_tank_long_pitch;         /* 0x44b174 */
int32_t tun_pitch_rate[4][2];        /* 0x44b098 */
int32_t tun_resupply_slots[4];       /* 0x44b0b8 */
int32_t tun_road_flags[17];          /* 0x44af2c[0x49..0x59]: road direction bits by terrain */
int8_t tun_heli_lift_z[56];          /* 0x44b190: obj+0x70 bob by altitude */
int8_t tun_heli_lift_tilt[56];       /* 0x44b1c8: state+0x88 by altitude */
uint8_t loadout_default[20];         /* 0x4438b8 (bytes 12..15 are overwritten by the level VHCL defaults) */
uint8_t bunker_menu_nav[4][4];       /* 0x43f1fc stride 0x28: up, down, left, right */
BunkerStep bunker_scripts[4][9];     /* bunker zoom scripts (menu table 0x43f1d8 +0x20), 0-terminated */
static const int bunker_script_len[4] = { 8, 6, 6, 8 };

/* ==== combat tables (src/game/weapon.c, effect.c) ==== */
/* explosion descriptors by projectile hit kind (0 ground, 1 water, 2 road, 3 object, 4 static) */
uint32_t expl_tab_450a48[6];
uint32_t expl_tab_450a60[6];         /* also the grenade table (GrenadeDestroy 0x4319d0) */
uint32_t expl_tab_vehicle[4];        /* 0x44b0c8: vehicle death explosion by type */
uint32_t snd_expl_tab[40];           /* 0x43ede0: explosion script sound events */
uint32_t snd_grenade_tab[3];         /* 0x43ee2c */
ProjType proj_types[12];             /* projectile type table 0x450a78 (12 x 0x3c) */

/* debris (FWall) programs: DebrisInit 0x4344b0 arg; steps dispatched through 0x454ee8 */
static DebrisStep dstep_44a000[5];
static DebrisStep dstep_44a748[9];
static DebrisStep dstep_44a868[9];
static DebrisStep dstep_4546b8[3];
static DebrisStep dstep_454740[7];
static DebrisStep dstep_454820[3];
static DebrisStep dstep_4548c8[9];
static DebrisStep dstep_4549e8[8];
static DebrisStep dstep_454c50[1];
static DebrisStep dstep_454c88[2];
static DebrisStep dstep_454cf0[2];
static DebrisStep dstep_454d48[2];
static DebrisStep dstep_454d88[2];
DebrisDef debris_44a0a0, debris_44a988, debris_44a99c, debris_454718, debris_4548a0, debris_4548b4;
DebrisDef debris_454be8, debris_454bfc, debris_454c28, debris_454c3c, debris_454c70, debris_454cc8;
DebrisDef debris_454cdc, debris_454d30, debris_454dc8, debris_454ddc, debris_454df0, debris_454e04;
typedef struct { DebrisDef *d; uint32_t addr; DebrisStep *steps; int nsteps; } DebrisDesc;
static const DebrisDesc debris_descs[18] = {
    { &debris_44a0a0, 0x44a0a0, dstep_44a000, 5 },
    { &debris_44a988, 0x44a988, dstep_44a748, 9 },
    { &debris_44a99c, 0x44a99c, dstep_44a868, 9 },
    { &debris_454718, 0x454718, dstep_4546b8, 3 },
    { &debris_4548a0, 0x4548a0, dstep_454740, 7 },
    { &debris_4548b4, 0x4548b4, dstep_454820, 3 },
    { &debris_454be8, 0x454be8, dstep_4548c8, 9 },
    { &debris_454bfc, 0x454bfc, dstep_4549e8, 8 },
    { &debris_454c28, 0x454c28, dstep_4548c8, 9 },
    { &debris_454c3c, 0x454c3c, dstep_4549e8, 8 },
    { &debris_454c70, 0x454c70, dstep_454c50, 1 },
    { &debris_454cc8, 0x454cc8, dstep_454c88, 2 },
    { &debris_454cdc, 0x454cdc, dstep_454c88, 1 },
    { &debris_454d30, 0x454d30, dstep_454cf0, 2 },
    { &debris_454dc8, 0x454dc8, dstep_454d48, 2 },
    { &debris_454ddc, 0x454ddc, dstep_454d88, 2 },
    { &debris_454df0, 0x454df0, dstep_454d48, 1 },
    { &debris_454e04, 0x454e04, dstep_454d88, 1 },
};
const DebrisDef *debris_sets[10][4];      /* 0x454e18: debris class by face flag bits 8-9 */
const DebrisDef *debris_set_tower[4];     /* 0x454730 (TowerDestroyed) */

/* weapon geometry / tunables */
int32_t muzzle_tank[2][3];            /* 0x44c6f8 barrel tip, 0x44c704 turret pivot */
int32_t msv_muzzle_raw[16];           /* 0x44d088: tube offsets (3 x 3, overlapping) + [10] 0x44d0b0 rocket/flash points */
int32_t muzzle_heli[2][6];            /* 0x44f218 / 0x44f230: offset + flash offset (L/R) */
int32_t tun_msv_pitch_lob, tun_msv_pitch_flat;   /* 0x44b17c / 0x44b180 */
int32_t tun_dmissile_turn, tun_dmissile_pitch;   /* 0x4509ec / 0x4509f0 */
int32_t tun_gravity, tun_fall_max;    /* 0x4546b0 / 0x4546b4 (FUN_004337d0) */
int32_t tun_bridge[7];                /* 0x44a128..0x44a140 bridge debris randomness */
int32_t bridge_debris_verts[2][4][3]; /* 0x44a0b8 (V bridge) / 0x44a0e8 (H), patched per piece */

/* ---- code addresses referenced by the tables -> port functions / enums ---- */
typedef struct { uint32_t va; VehHookFn hook; VehMoveFn move; VehWaterFn water; VehFireFn fire; VehInitFn init; VehDamageFn damage; } VehFn;
static const VehFn veh_fns[] = {
    { 0x429f20, .hook = veh_tank_launch },
    { 0x42a250, .hook = veh_msv_launch },
    { 0x42a410, .hook = veh_jeep_launch },
    { 0x42b3c0, .hook = veh_heli_spinup },
    { 0x42ab90, .hook = veh_jeep_dock },
    { 0x42b600, .hook = veh_heli_dock },
    { 0x42a670, .move = veh_move_jeep },
    { 0x42abe0, .move = veh_move_heli },
    { 0x4299e0, .water = veh_water_normal },
    { 0x429d30, .fire = veh_tank_fire },
    { 0x42aa00, .fire = veh_jeep_grenade },
    { 0x42aae0, .fire = veh_jeep_boat },
    { 0x42ab70, .fire = veh_jeep_drop_flag },
    { 0x42a010, .fire = veh_msv_fire },
    { 0x42a310, .fire = veh_msv_mine },
    { 0x42b100, .fire = veh_heli_fire },
    { 0x42b2a0, .fire = veh_heli_missile },
    { 0x42b5e0, .init = veh_heli_init },
    { 0x42b330, .damage = veh_heli_damaged },
};
static const uint32_t bno_hit_fns[] = { 0x0, 0x41f290, 0x41f260, 0x41f340, 0x41f6a0, 0x4247e0 };   /* BHIT_* */
static const uint32_t bno_des_fns[] = { 0x0, 0x417a00, 0x423510, 0x424170, 0x41f9a0 };   /* BDES_* */
static const uint32_t proj_cls_va[3] = { 0x450950, 0x4509a0, 0x4509f8 };
static const ObjClass *const proj_cls[3] = { &class_missle, &class_tracer, &class_death_missle };
static const uint32_t proj_expl_va[2] = { 0x450a48, 0x450a60 };
static const uint32_t *const proj_expl[2] = { expl_tab_450a48, expl_tab_450a60 };

/* ---- loader ---- */
static void fail(const char *what, uint32_t va)
{
    fprintf(stderr, "game_tables: unexpected %s at 0x%x in RFIRE.BIN\n", what, va);
    abort();
}

static void rd_s32(int32_t *dst, uint32_t va, int n) { for (int i = 0; i < n; i++) dst[i] = exe_s32(va + 4 * (uint32_t)i); }
static void rd_u32(uint32_t *dst, uint32_t va, int n) { for (int i = 0; i < n; i++) dst[i] = exe_u32(va + 4 * (uint32_t)i); }
static void rd_u8(uint8_t *dst, uint32_t va, int n) { for (int i = 0; i < n; i++) dst[i] = exe_u8(va + (uint32_t)i); }

static ShapePart *shape_at(uint32_t va)
{
    if (!va) return NULL;
    for (size_t i = 0; i < sizeof shape_descs / sizeof *shape_descs; i++)
        if (shape_descs[i].addr == va) return shape_descs[i].s;
    fail("shape part", va);
    return NULL;
}

static Gfx *gfx_at(uint32_t va)
{
    if (!va) return NULL;
    for (size_t i = 0; i < sizeof gfx_addrs / sizeof *gfx_addrs; i++)
        if (gfx_addrs[i] == va) return gfx_descs[i];
    fail("graphic", va);
    return NULL;
}

static const DebrisDef *debris_at(uint32_t va)
{
    if (!va) return NULL;
    for (size_t i = 0; i < sizeof debris_descs / sizeof *debris_descs; i++)
        if (debris_descs[i].addr == va) return debris_descs[i].d;
    fail("debris program", va);
    return NULL;
}

static const VehFn *veh_fn(uint32_t va)
{
    static const VehFn none;
    if (!va) return &none;
    for (size_t i = 0; i < sizeof veh_fns / sizeof *veh_fns; i++)
        if (veh_fns[i].va == va) return &veh_fns[i];
    fail("vehicle hook", va);
    return &none;
}

static uint8_t fn_index(const uint32_t *tab, int n, uint32_t va)
{
    for (int i = 0; i < n; i++) if (tab[i] == va) return (uint8_t)i;
    fail("handler", va);
    return 0;
}

static void load_shape(const ShapeDesc *d)
{
    ShapePart *s = d->s;
    uint32_t p = d->addr;
    s->type = exe_s32(p);
    s->next = shape_at(exe_u32(p + 4));
    s->b8 = exe_u8(p + 8); s->kind = exe_u8(p + 9); s->solid = exe_u8(p + 10); s->mask = exe_u8(p + 11);
    s->zlo = exe_s32(p + 0xc); s->zhi = exe_s32(p + 0x10);
    s->dx = exe_s32(p + 0x14); s->dy = exe_s32(p + 0x18);
    rd_s32(s->bbox, p + 0x1c, 4);
    s->nverts = 0; s->verts = NULL; s->nedges = 0; s->edges = NULL;
    if (d->v) {                                   /* types 3/4: vertex and edge lists */
        s->nverts = exe_s32(p + 0x2c);
        s->nedges = exe_s32(p + 0x34);
        uint32_t vp = exe_u32(p + 0x30), ep = exe_u32(p + 0x38);
        if (s->nverts > d->nv || s->nedges > d->ne) fail("shape size", p);
        for (int i = 0; i < s->nverts; i++) rd_s32(d->v[i], vp + 12 * (uint32_t)i, 3);
        if (ep) rd_u8(d->e, ep, s->nedges);
        s->verts = d->v;
        s->edges = d->e;
    }
    s->addr = p;
}

static void load_vehicle(VehicleDef *v, uint32_t t)
{
    uint32_t w[0xb8];
    rd_u32(w, t, 0xb8);
#define I(k) ((int32_t)w[k])
    v->type = I(0);
    v->name = exe_str(w[1]);
    v->launch_hook = veh_fn(w[5])->hook;
    v->move = veh_fn(w[6])->move;
    v->armour = I(9); v->hp = I(0xa);
    v->water_hook = veh_fn(w[0x13])->water;
    v->cam_flags = I(0x31);
    for (int i = 0; i < 24; i++) v->cam[i] = I(0x3a + i);
    v->gfx = gfx_at(w[0x52]); v->gfx_splash = gfx_at(w[0x53]); v->gfx_sink = gfx_at(w[0x55]);
    v->sink_depth = I(0x56); v->unk57 = I(0x57);
    v->gfx_wreck = gfx_at(w[0x58]); v->gfx_wreck2 = gfx_at(w[0x59]);
    v->max_fwd = I(0x5a); v->max_rev = I(0x5b); v->accel = I(0x5c); v->friction = I(0x5d); v->turn = I(0x5e);
    for (int i = 0; i < 3; i++) { v->fire[i] = veh_fn(w[0x5f + i])->fire; v->fire_arg[i] = I(0x62 + i); }
    for (int s = 0; s < 3; s++) {
        const uint32_t *x = &w[0x65 + 13 * s];
        WeaponDef *d = &v->weapon[s];
        d->proj = (int32_t)x[0];
        for (int k = 0; k < 3; k++) d->arg[k] = (int32_t)x[1 + k];
        d->reload = (int32_t)x[4]; d->ammo = (int32_t)x[5]; d->hud_kind = (int32_t)x[6];
        for (int k = 0; k < 4; k++) d->hud_rect[k] = (int32_t)x[7 + k];
        d->hud_scale = (int32_t)x[11]; d->w12 = (int32_t)x[12];
    }
    v->init_hook = veh_fn(w[0x8c])->init;
    v->death_hook = veh_fn(w[0x8d])->hook;
    v->damage_hook = veh_fn(w[0x8e])->damage;
    v->snd_engine = w[0x90]; v->snd_91 = I(0x91); v->snd_92 = I(0x92);
    v->cam_attach = w[0x94]; v->dock_radius = I(0x95);
    v->dock_hook = veh_fn(w[0x96])->hook;
    v->wreck_friction = I(0x97); v->respawn_delay = I(0x98);
    v->radar_99 = I(0x99); v->radar_icon[0] = w[0x9a]; v->radar_icon[1] = w[0x9b];
    for (int i = 0; i < 5; i++) v->hud9[i] = I(0x9c + i);
    v->hud_icon[0] = I(0xa1); v->hud_icon[1] = I(0xa2);
    for (int i = 0; i < 3; i++) v->unk_a3[i] = I(0xa3 + i);
    v->arrow_enable = w[0xa6];
    for (int i = 0; i < 4; i++) { v->unk_a7[i] = I(0xa7 + i); v->arrow_box[i] = I(0xab + i); }
    v->music = w[0xaf];
    for (int i = 0; i < 8; i++) v->tail[i] = I(0xb0 + i);
#undef I
}

static void game_tables_load(void)
{
    for (size_t i = 0; i < sizeof shape_descs / sizeof *shape_descs; i++) load_shape(&shape_descs[i]);
    for (size_t i = 0; i < sizeof gfx_addrs / sizeof *gfx_addrs; i++) {
        uint32_t g = gfx_addrs[i], adj = exe_u32(g + 0x28);
        if (adj != 0 && adj != 0x41f210) fail("graphic adjust hook", g);
        *gfx_descs[i] = (Gfx){ g, shape_at(exe_u32(g + 8)), exe_s32(g + 12), adj ? GADJ_JITTER : GADJ_NONE };
    }
    for (int i = 0; i < BNO_COUNT; i++) {
        uint32_t a = 0x451438 + 0x38 * (uint32_t)i;
        BnoDef *b = &bno_defs[i];
        b->name = exe_str(exe_u32(a + 4));
        b->gfx = gfx_at(exe_u32(a + 8));
        b->flags = exe_u32(a + 0xc);
        b->terrain = exe_u8(a + 0x10); b->hp = exe_u8(a + 0x11);
        b->hit = fn_index(bno_hit_fns, (int)(sizeof bno_hit_fns / sizeof *bno_hit_fns), exe_u32(a + 0x14));
        b->destroy = fn_index(bno_des_fns, (int)(sizeof bno_des_fns / sizeof *bno_des_fns), exe_u32(a + 0x1c));
        b->armour = exe_s32(a + 0x20); b->mult = exe_s32(a + 0x24);
        b->expl_crush = exe_u32(a + 0x28); b->expl = exe_u32(a + 0x2c);
        b->dest_terrain = exe_u8(a + 0x30); b->dest_bno = exe_u8(a + 0x31);
    }
    for (int t = 0; t < 24; t++) {
        uint32_t a = 0x443558 + 8 * (uint32_t)t;
        shore_shapes[t] = (ShoreShape){ exe_u8(a), exe_s8(a + 1), t >= 4 ? shape_at(exe_u32(a + 4)) : NULL };
    }
    rd_s32(&shore_boxes[0][0], 0x443618, 12 * 4);
    for (int i = 0; i < 4; i++) load_vehicle(&vehicle_defs[i], exe_u32(0x44afc8 + 4 * (uint32_t)i));

    tun_launch_ticks = exe_s32(0x44b178);
    tun_idle_drone_ticks = exe_s32(0x44afa8);
    tun_door_anim_rate = exe_s32(0x44afdc);
    tun_heli_takeoff_dx = exe_s32(0x44b184);
    tun_heli_turn_up = exe_s32(0x44b188); tun_heli_turn_down = exe_s32(0x44b18c);
    tun_tank_long_pitch = exe_s32(0x44b174);
    rd_s32(&tun_pitch_rate[0][0], 0x44b098, 8);
    rd_s32(tun_resupply_slots, 0x44b0b8, 4);
    rd_s32(tun_road_flags, 0x44af2c + 4 * 0x49, 17);
    rd_u8((uint8_t *)tun_heli_lift_z, 0x44b190, 56);
    rd_u8((uint8_t *)tun_heli_lift_tilt, 0x44b1c8, 56);
    rd_u8(loadout_default, 0x4438b8, 20);
    for (int i = 0; i < 4; i++) {
        uint32_t m = 0x43f1d8 + 0x28 * (uint32_t)i;
        rd_u8(bunker_menu_nav[i], m + 0x24, 4);
        uint32_t p = exe_u32(m + 0x20);
        for (int k = 0; k < 9; k++) bunker_scripts[i][k] = (BunkerStep){ 0, 0, 0, 0, 0 };
        for (int k = 0; k < bunker_script_len[i]; k++) {
            uint32_t e = p + 20 * (uint32_t)k;
            bunker_scripts[i][k] = (BunkerStep){ exe_u32(e), exe_s32(e + 4), exe_s32(e + 8), exe_s32(e + 12), exe_s32(e + 16) };
        }
        if (exe_s32(p + 20 * (uint32_t)bunker_script_len[i])) fail("bunker script length", p);
    }

    rd_u32(expl_tab_450a48, 0x450a48, 6);
    rd_u32(expl_tab_450a60, 0x450a60, 6);
    rd_u32(expl_tab_vehicle, 0x44b0c8, 4);
    rd_u32(snd_expl_tab, 0x43ede0, 40);
    rd_u32(snd_grenade_tab, 0x43ee2c, 3);
    for (int i = 0; i < 12; i++) {
        uint32_t a = 0x450a78 + 0x3c * (uint32_t)i;
        ProjType *t = &proj_types[i];
        uint32_t c = exe_u32(a), x = exe_u32(a + 0x34);
        t->cls = c == proj_cls_va[0] ? proj_cls[0] : c == proj_cls_va[1] ? proj_cls[1] : c == proj_cls_va[2] ? proj_cls[2] : NULL;
        t->expl = x == proj_expl_va[0] ? proj_expl[0] : x == proj_expl_va[1] ? proj_expl[1] : NULL;
        if (!t->cls || !t->expl) fail("projectile type", a);
        t->index = exe_s32(a + 4); t->flags = exe_u32(a + 8); t->speed = exe_s32(a + 12);
        t->snd = exe_u32(a + 0x18); t->impact = exe_u32(a + 0x1c) != 0;
        t->damage = exe_s32(a + 0x24); t->pitch_rate = exe_s32(a + 0x28);
        t->gfx = gfx_at(exe_u32(a + 0x2c)); t->shadow = gfx_at(exe_u32(a + 0x30));
        t->life = exe_u8(a + 0x38); t->nframes = exe_u8(a + 0x39); t->period = exe_u8(a + 0x3a); t->splash = exe_u8(a + 0x3b);
    }
    for (size_t i = 0; i < sizeof debris_descs / sizeof *debris_descs; i++) {
        const DebrisDesc *d = &debris_descs[i];
        uint32_t p = d->addr, sp = exe_u32(p + 16);
        if (exe_s32(p + 12) != d->nsteps) fail("debris step count", p);
        for (int k = 0; k < d->nsteps; k++) rd_s32(&d->steps[k].op, sp + 32 * (uint32_t)k, 8);
        *d->d = (DebrisDef){ exe_s32(p), exe_s32(p + 4), exe_s32(p + 8), d->nsteps, d->steps, p };
    }
    for (int k = 0; k < 10; k++)
        for (int j = 0; j < 4; j++) debris_sets[k][j] = debris_at(exe_u32(0x454e18 + 16 * (uint32_t)k + 4 * (uint32_t)j));
    for (int j = 0; j < 4; j++) debris_set_tower[j] = debris_at(exe_u32(0x454730 + 4 * (uint32_t)j));

    rd_s32(&muzzle_tank[0][0], 0x44c6f8, 6);
    rd_s32(msv_muzzle_raw, 0x44d088, 16);
    rd_s32(&muzzle_heli[0][0], 0x44f218, 12);
    tun_msv_pitch_lob = exe_s32(0x44b17c); tun_msv_pitch_flat = exe_s32(0x44b180);
    tun_dmissile_turn = exe_s32(0x4509ec); tun_dmissile_pitch = exe_s32(0x4509f0);
    tun_gravity = exe_s32(0x4546b0); tun_fall_max = exe_s32(0x4546b4);
    rd_s32(tun_bridge, 0x44a128, 7);
    rd_s32(&bridge_debris_verts[0][0][0], 0x44a0b8, 24);
}
EXE_LOADER(game_tables_load)
