/* Generated by tools/gen_rules_tables.py from the layout of RFIRE.BIN. Do not edit.
   Shapes, graphics and tunables of the MAN (0x43fb10), Gate (0x44ade0) and Flag (0x44ae30) classes.
   Addresses only: the contents are read from the user's RFIRE.BIN at start-up (exe.c, rules_tables_load). */
#include <stddef.h>
#include "rules.h"
#include "../exe.h"

static ShapePart rshp_43f8c0;
static ShapePart rshp_43f880;
static ShapePart rshp_44e6f8;
static ShapePart rshp_442930;
static ShapePart rshp_44296c;
static ShapePart rshp_442df8;
static ShapePart rshp_442e34;
static ShapePart rshp_4424f8;
static ShapePart *const rshp_descs[8] = { &rshp_43f8c0, &rshp_43f880, &rshp_44e6f8, &rshp_442930, &rshp_44296c, &rshp_442df8, &rshp_442e34, &rshp_4424f8 };
static const uint32_t rshp_addrs[8] = { 0x43f8c0, 0x43f880, 0x44e6f8, 0x442930, 0x44296c, 0x442df8, 0x442e34, 0x4424f8 };

/* gate door parts (heap copies are made per Gate object by GateInit 0x423cd0) */
const ShapePart *const gate_door_parts[2] = { &rshp_442930, &rshp_442df8 };   /* H (0x4428a8+0x88), V (0x442d70+0x88) */
ShapePart *const gate_zone_part = &rshp_4424f8;   /* the pickup zone of BNO 43/44 (GateUpdate: parent still near) */

Gfx rgfx_43f900;   /* MAN walking (Model_DrawMan 0x4061c0) */
Gfx rgfx_43f998;   /* MAN swimming (0x406280) */
Gfx rgfx_43fa30;   /* dead man (Stay, Model_DrawStatic) */
Gfx rgfx_44e740;   /* Flag on the ground (0x42f740) */
Gfx rgfx_44e610;   /* Flag carried by a jeep (0x42f6e0) */
Gfx rgfx_4428a8;   /* Gate (copy of the graphic, door parts) */
Gfx rgfx_442d70;   /* Gate (copy of the graphic, door parts) */

/* MAN tunables */
int32_t man_walk_speed;          /* DAT_0043fa74 px/tick */
int32_t man_anim_rate;           /* DAT_0043fa7c frames/tick */
int32_t man_grenade_min;         /* DAT_0043fa98 min distance for a grenade */
int8_t man_grenades[16];         /* DAT_0043fa88 by RandRange(16) */
int32_t man_unstick[8][3];       /* DAT_0043fab0 */
int32_t flag_carry_offset[3];    /* DAT_0044e558 (rotated by the jeep heading) */
int32_t flag_pitch_bias, flag_pitch_shift;   /* DAT_0044e734 / DAT_0044e738 */
int32_t win_movie_by_level[10];  /* DAT_004559e0 */
int32_t win_banner_pos[4][2];    /* DAT_00455a18 (x, y; -1 = centred; doubled in 640x480) */

static ShapePart *rshp_at(uint32_t va)
{
    for (int i = 0; va && i < (int)(sizeof rshp_addrs / sizeof *rshp_addrs); i++)
        if (rshp_addrs[i] == va) return rshp_descs[i];
    return NULL;
}

static void rd_s32(int32_t *dst, uint32_t va, int n) { for (int i = 0; i < n; i++) dst[i] = exe_s32(va + 4 * (uint32_t)i); }

static void rules_tables_load(void)
{
    for (int i = 0; i < (int)(sizeof rshp_addrs / sizeof *rshp_addrs); i++) {    /* type 2 (AABB) parts */
        uint32_t p = rshp_addrs[i];
        ShapePart *s = rshp_descs[i];
        *s = (ShapePart){ 0 };
        s->type = exe_s32(p);
        s->next = rshp_at(exe_u32(p + 4));
        s->b8 = exe_u8(p + 8); s->kind = exe_u8(p + 9); s->solid = exe_u8(p + 10); s->mask = exe_u8(p + 11);
        s->zlo = exe_s32(p + 0xc); s->zhi = exe_s32(p + 0x10);
        s->dx = exe_s32(p + 0x14); s->dy = exe_s32(p + 0x18);
        rd_s32(s->bbox, p + 0x1c, 4);
        s->addr = p;
    }
    Gfx *const g[] = { &rgfx_43f900, &rgfx_43f998, &rgfx_43fa30, &rgfx_44e740, &rgfx_44e610 };
    const uint32_t ga[] = { 0x43f900, 0x43f998, 0x43fa30, 0x44e740, 0x44e610 };
    for (size_t i = 0; i < sizeof g / sizeof *g; i++)
        *g[i] = (Gfx){ ga[i], rshp_at(exe_u32(ga[i] + 8)), exe_s32(ga[i] + 12), GADJ_NONE };
    Gfx *const gates[] = { &rgfx_4428a8, &rgfx_442d70 };
    const uint32_t gta[] = { 0x4428a8, 0x442d70 };
    for (size_t i = 0; i < sizeof gates / sizeof *gates; i++)
        *gates[i] = (Gfx){ gta[i], rshp_at(gta[i] + 0x88), exe_s32(gta[i] + 12), GADJ_NONE };
    man_walk_speed = exe_s32(0x43fa74);
    man_anim_rate = exe_s32(0x43fa7c);
    man_grenade_min = exe_s32(0x43fa98);
    for (int i = 0; i < 16; i++) man_grenades[i] = exe_s8(0x43fa88 + (uint32_t)i);
    rd_s32(&man_unstick[0][0], 0x43fab0, 24);
    rd_s32(flag_carry_offset, 0x44e558, 3);
    flag_pitch_bias = exe_s32(0x44e734); flag_pitch_shift = exe_s32(0x44e738);
    rd_s32(win_movie_by_level, 0x4559e0, 10);
    rd_s32(&win_banner_pos[0][0], 0x455a18, 8);
}
EXE_LOADER(rules_tables_load)
