/* Generated by tools/gen_models_c.py from the layout of RFIRE.BIN. Do not edit.
   All 3D model parts of RFIRE.BIN .data (see docs/render.md section 7): addresses and counts only;
   the geometry is read from the user's RFIRE.BIN at start-up (exe.c, models_load below). */
#include "model.h"
#include "../exe.h"
#include <string.h>

ModelPart model_parts[MODEL_PART_COUNT];
RenderBno render_bno[RENDER_BNO_COUNT];
const ModelPart *model_projectile_model[12];
const ModelPart *model_projectile_shadow[12];

/* vertex / face / face-order buffers (part address; counts from the part header +0x2c / +0x34) */
static int32_t v_43f900[8][3];
static ModelFace f_43f900[2];
static int32_t v_43f998[4][3];
static ModelFace f_43f998[1];
static int32_t v_43fa30[4][3];
static ModelFace f_43fa30[1];
static int32_t v_43fbb0[4][3];
static ModelFace f_43fbb0[1];
static int32_t v_441338[4][3];
static ModelFace f_441338[1];
static int32_t v_4414f0[8][3];
static ModelFace f_4414f0[5];
static int32_t v_441538[8][3];
static ModelFace f_441538[5];
static int32_t v_4415b0[4][3];
static ModelFace f_4415b0[1];
static int32_t v_441698[8][3];
static ModelFace f_441698[5];
static int32_t v_441840[12][3];
static ModelFace f_441840[5];
static int8_t o_441840_0[5], o_441840_1[6], o_441840_2[6], o_441840_3[6], o_441840_4[6], o_441840_5[6], o_441840_6[5], o_441840_7[5];
static int32_t v_4418a0[12][3];
static ModelFace f_4418a0[5];
static int8_t o_4418a0_0[5], o_4418a0_1[6], o_4418a0_2[6], o_4418a0_3[6], o_4418a0_4[6], o_4418a0_5[6], o_4418a0_6[5], o_4418a0_7[5];
static int32_t v_4419a0[12][3];
static ModelFace f_4419a0[5];
static int32_t v_441a78[4][3];
static ModelFace f_441a78[1];
static int32_t v_441ac0[4][3];
static ModelFace f_441ac0[1];
static int32_t v_441d68[8][3];
static ModelFace f_441d68[3];
static int32_t v_441db0[12][3];
static ModelFace f_441db0[4];
static int32_t v_441df8[12][3];
static ModelFace f_441df8[4];
static int32_t v_441fa0[16][3];
static ModelFace f_441fa0[5];
static int32_t v_442278[8][3];
static ModelFace f_442278[3];
static int32_t v_4422c0[12][3];
static ModelFace f_4422c0[4];
static int32_t v_442308[12][3];
static ModelFace f_442308[4];
static int32_t v_4424b0[16][3];
static ModelFace f_4424b0[5];
static int32_t v_4428a8[15][3];
static ModelFace f_4428a8[7];
static int32_t v_4428ec[15][3];
static ModelFace f_4428ec[7];
static int32_t v_442d70[16][3];
static ModelFace f_442d70[8];
static int32_t v_442db4[16][3];
static ModelFace f_442db4[8];
static int32_t v_442e98[4][3];
static ModelFace f_442e98[1];
static int32_t v_442fd8[4][3];
static ModelFace f_442fd8[1];
static int32_t v_443040[4][3];
static ModelFace f_443040[1];
static int32_t v_4431f8[12][3];
static ModelFace f_4431f8[5];
static int32_t v_4440a8[12][3];
static ModelFace f_4440a8[3];
static int32_t v_4440f0[12][3];
static ModelFace f_4440f0[3];
static int32_t v_444178[4][3];
static ModelFace f_444178[1];
static int32_t v_444200[4][3];
static ModelFace f_444200[1];
static int32_t v_4443c8[8][3];
static ModelFace f_4443c8[2];
static int32_t v_444490[8][3];
static ModelFace f_444490[2];
static int32_t v_444588[4][3];
static ModelFace f_444588[1];
static int32_t v_4445d0[4][3];
static ModelFace f_4445d0[1];
static int32_t v_444698[4][3];
static ModelFace f_444698[1];
static int32_t v_444780[8][3];
static ModelFace f_444780[2];
static int32_t v_4448e8[8][3];
static ModelFace f_4448e8[2];
static int32_t v_4449d0[8][3];
static ModelFace f_4449d0[2];
static int32_t v_444b38[8][3];
static ModelFace f_444b38[2];
static int32_t v_444cd0[4][3];
static ModelFace f_444cd0[1];
static int32_t v_444d18[8][3];
static ModelFace f_444d18[3];
static int32_t v_444ed0[4][3];
static ModelFace f_444ed0[1];
static int32_t v_444f18[4][3];
static ModelFace f_444f18[1];
static int32_t v_444f60[4][3];
static ModelFace f_444f60[1];
static int32_t v_444fa8[4][3];
static ModelFace f_444fa8[1];
static int32_t v_4450f8[4][3];
static ModelFace f_4450f8[1];
static int32_t v_44513c[4][3];
static ModelFace f_44513c[1];
static int32_t v_445180[4][3];
static ModelFace f_445180[1];
static int32_t v_4451c4[4][3];
static ModelFace f_4451c4[1];
static int32_t v_445450[12][3];
static ModelFace f_445450[5];
static int32_t v_445494[12][3];
static ModelFace f_445494[5];
static int32_t v_4454d8[12][3];
static ModelFace f_4454d8[5];
static int32_t v_44551c[12][3];
static ModelFace f_44551c[5];
static int32_t v_4455e0[4][3];
static ModelFace f_4455e0[1];
static int32_t v_445624[4][3];
static ModelFace f_445624[1];
static int32_t v_445668[4][3];
static ModelFace f_445668[1];
static int32_t v_4456ac[4][3];
static ModelFace f_4456ac[1];
static int32_t v_445bb8[4][3];
static ModelFace f_445bb8[1];
static int32_t v_445bfc[4][3];
static ModelFace f_445bfc[1];
static int32_t v_445c40[4][3];
static ModelFace f_445c40[1];
static int32_t v_445c84[4][3];
static ModelFace f_445c84[1];
static int32_t v_445cc8[4][3];
static ModelFace f_445cc8[1];
static int32_t v_445d0c[4][3];
static ModelFace f_445d0c[1];
static int32_t v_445d50[4][3];
static ModelFace f_445d50[1];
static int32_t v_445d98[24][3];
static ModelFace f_445d98[10];
static int32_t v_445ddc[24][3];
static ModelFace f_445ddc[10];
static int32_t v_445e20[24][3];
static ModelFace f_445e20[10];
static int32_t v_445e64[24][3];
static ModelFace f_445e64[10];
static int32_t v_445fa8[4][3];
static ModelFace f_445fa8[2];
static int32_t v_446070[12][3];
static ModelFace f_446070[5];
static int32_t v_4461d0[4][3];
static ModelFace f_4461d0[1];
static int32_t v_446258[12][3];
static ModelFace f_446258[4];
static int32_t v_4462c0[4][3];
static ModelFace f_4462c0[1];
static int32_t v_446348[7][3];
static ModelFace f_446348[2];
static int32_t v_446570[16][3];
static ModelFace f_446570[7];
static int32_t v_446738[16][3];
static ModelFace f_446738[6];
static int32_t v_4467a0[4][3];
static ModelFace f_4467a0[1];
static int32_t v_446998[9][3];
static ModelFace f_446998[8];
static int32_t v_446a00[4][3];
static ModelFace f_446a00[1];
static int32_t v_446b08[8][3];
static ModelFace f_446b08[4];
static int32_t v_446c60[4][3];
static ModelFace f_446c60[1];
static int32_t v_446d28[8][3];
static ModelFace f_446d28[4];
static int32_t v_446e60[4][3];
static ModelFace f_446e60[1];
static int32_t v_446ea8[4][3];
static ModelFace f_446ea8[1];
static int32_t v_4470d0[4][3];
static ModelFace f_4470d0[1];
static int32_t v_447118[4][3];
static ModelFace f_447118[1];
static int32_t v_447160[4][3];
static ModelFace f_447160[1];
static int32_t v_4471a8[4][3];
static ModelFace f_4471a8[1];
static int32_t v_447230[4][3];
static ModelFace f_447230[1];
static int32_t v_447278[4][3];
static ModelFace f_447278[1];
static int32_t v_447908[8][3];
static ModelFace f_447908[5];
static int32_t v_44794c[8][3];
static ModelFace f_44794c[5];
static int32_t v_447990[8][3];
static ModelFace f_447990[5];
static int32_t v_4479d4[8][3];
static ModelFace f_4479d4[5];
static int32_t v_447a18[8][3];
static ModelFace f_447a18[5];
static int32_t v_447a5c[8][3];
static ModelFace f_447a5c[5];
static int32_t v_447aa0[8][3];
static ModelFace f_447aa0[5];
static int32_t v_447ae4[8][3];
static ModelFace f_447ae4[5];
static int32_t v_447cb8[4][3];
static ModelFace f_447cb8[1];
static int32_t v_447d00[8][3];
static ModelFace f_447d00[5];
static int32_t v_447d68[4][3];
static ModelFace f_447d68[1];
static int32_t v_447dd0[4][3];
static ModelFace f_447dd0[1];
static int32_t v_448268[28][3];
static ModelFace f_448268[11];
static int32_t v_4482b0[28][3];
static ModelFace f_4482b0[11];
static int32_t v_448708[28][3];
static ModelFace f_448708[11];
static int32_t v_448750[28][3];
static ModelFace f_448750[11];
static int32_t v_4487d8[4][3];
static ModelFace f_4487d8[1];
static int32_t v_44881c[4][3];
static ModelFace f_44881c[1];
static int32_t v_4488e0[4][3];
static ModelFace f_4488e0[1];
static int32_t v_448924[4][3];
static ModelFace f_448924[1];
static int32_t v_448968[4][3];
static ModelFace f_448968[1];
static int32_t v_448df8[18][3];
static ModelFace f_448df8[5];
static int32_t v_448e40[18][3];
static ModelFace f_448e40[5];
static int32_t v_448e88[18][3];
static ModelFace f_448e88[5];
static int32_t v_448ef0[4][3];
static ModelFace f_448ef0[1];
static int32_t v_4491c0[11][3];
static ModelFace f_4491c0[4];
static int32_t v_449208[11][3];
static ModelFace f_449208[4];
static int32_t v_449270[4][3];
static ModelFace f_449270[1];
static int32_t v_449318[4][3];
static ModelFace f_449318[1];
static int32_t v_4493b0[4][3];
static ModelFace f_4493b0[1];
static int32_t v_449478[4][3];
static ModelFace f_449478[1];
static int32_t v_4495c0[8][3];
static ModelFace f_4495c0[3];
static int32_t v_449628[4][3];
static ModelFace f_449628[1];
static int32_t v_449730[8][3];
static ModelFace f_449730[3];
static int32_t v_449798[4][3];
static ModelFace f_449798[1];
static int32_t v_4498a0[8][3];
static ModelFace f_4498a0[3];
static int32_t v_449908[4][3];
static ModelFace f_449908[1];
static int32_t v_4499a0[4][3];
static ModelFace f_4499a0[1];
static int32_t v_449a08[4][3];
static ModelFace f_449a08[1];
static int32_t v_449aa0[4][3];
static ModelFace f_449aa0[1];
static int32_t v_449ae8[4][3];
static ModelFace f_449ae8[1];
static int32_t v_449d90[4][3];
static ModelFace f_449d90[1];
static int32_t v_449dd8[4][3];
static ModelFace f_449dd8[1];
static int32_t v_449e20[4][3];
static ModelFace f_449e20[1];
static int32_t v_449e68[4][3];
static ModelFace f_449e68[1];
static int32_t v_449eb0[4][3];
static ModelFace f_449eb0[1];
static int32_t v_449ef8[4][3];
static ModelFace f_449ef8[1];
static int32_t v_449f40[4][3];
static ModelFace f_449f40[1];
static int32_t v_449f88[4][3];
static ModelFace f_449f88[1];
static int32_t v_44a2d8[4][3];
static ModelFace f_44a2d8[1];
static int32_t v_44a360[12][3];
static ModelFace f_44a360[5];
static int32_t v_44a3e8[4][3];
static ModelFace f_44a3e8[2];
static int32_t v_44a610[16][3];
static ModelFace f_44a610[9];
static int32_t v_44b000[4][3];
static ModelFace f_44b000[1];
static int32_t v_44c668[4][3];
static ModelFace f_44c668[1];
static int32_t v_44c6b0[4][3];
static ModelFace f_44c6b0[2];
static int32_t v_44c9b0[4][3];
static ModelFace f_44c9b0[1];
static int32_t v_44ccb0[22][3];
static ModelFace f_44ccb0[8];
static int8_t o_44ccb0_0[9], o_44ccb0_1[9], o_44ccb0_2[9], o_44ccb0_3[9], o_44ccb0_4[9], o_44ccb0_5[9], o_44ccb0_6[9], o_44ccb0_7[9];
static int32_t v_44cd10[24][3];
static ModelFace f_44cd10[6];
static int8_t o_44cd10_0[7], o_44cd10_1[7], o_44cd10_2[7], o_44cd10_3[7], o_44cd10_4[7], o_44cd10_5[7], o_44cd10_6[7], o_44cd10_7[7];
static int32_t v_44cdc0[4][3];
static ModelFace f_44cdc0[1];
static int32_t v_44ce48[8][3];
static ModelFace f_44ce48[2];
static int32_t v_44ce90[24][3];
static ModelFace f_44ce90[6];
static int8_t o_44ce90_0[7], o_44ce90_1[7], o_44ce90_2[7], o_44ce90_3[7], o_44ce90_4[7], o_44ce90_5[7], o_44ce90_6[7], o_44ce90_7[7];
static int32_t v_44cfe0[12][3];
static ModelFace f_44cfe0[3];
static int32_t v_44d3d0[4][3];
static ModelFace f_44d3d0[1];
static int32_t v_44d650[52][3];
static ModelFace f_44d650[14];
static int8_t o_44d650_0[15], o_44d650_1[15], o_44d650_2[15], o_44d650_3[15], o_44d650_4[15], o_44d650_5[15], o_44d650_6[15], o_44d650_7[15];
static int32_t v_44d700[4][3];
static ModelFace f_44d700[1];
static int32_t v_44d788[8][3];
static ModelFace f_44d788[2];
static int32_t v_44d7d0[52][3];
static ModelFace f_44d7d0[14];
static int8_t o_44d7d0_0[15], o_44d7d0_1[15], o_44d7d0_2[15], o_44d7d0_3[15], o_44d7d0_4[15], o_44d7d0_5[15], o_44d7d0_6[15], o_44d7d0_7[15];
static int32_t v_44d920[12][3];
static ModelFace f_44d920[3];
static int32_t v_44dca8[4][3];
static ModelFace f_44dca8[1];
static int32_t v_44dfb0[48][3];
static ModelFace f_44dfb0[12];
static int8_t o_44dfb0_0[13], o_44dfb0_1[13], o_44dfb0_2[13], o_44dfb0_3[13], o_44dfb0_4[13], o_44dfb0_5[13], o_44dfb0_6[13], o_44dfb0_7[13];
static int32_t v_44e070[44][3];
static ModelFace f_44e070[11];
static int8_t o_44e070_0[12], o_44e070_1[12], o_44e070_2[12], o_44e070_3[12], o_44e070_4[12], o_44e070_5[12], o_44e070_6[12], o_44e070_7[12];
static int32_t v_44e110[6][3];
static ModelFace f_44e110[2];
static int32_t v_44e1a8[4][3];
static ModelFace f_44e1a8[1];
static int32_t v_44e240[4][3];
static ModelFace f_44e240[1];
static int32_t v_44e328[8][3];
static ModelFace f_44e328[2];
static int32_t v_44e3c0[36][3];
static ModelFace f_44e3c0[9];
static int8_t o_44e3c0_0[10], o_44e3c0_1[10], o_44e3c0_2[10], o_44e3c0_3[10], o_44e3c0_4[10], o_44e3c0_5[10], o_44e3c0_6[10], o_44e3c0_7[10];
static int32_t v_44e510[12][3];
static ModelFace f_44e510[3];
static int32_t v_44e610[8][3];
static ModelFace f_44e610[2];
static int32_t v_44e740[8][3];
static ModelFace f_44e740[2];
static int32_t v_44e9b8[4][3];
static ModelFace f_44e9b8[1];
static int32_t v_44ea00[6][3];
static ModelFace f_44ea00[2];
static int32_t v_44ee68[44][3];
static ModelFace f_44ee68[12];
static int8_t o_44ee68_0[13], o_44ee68_1[13], o_44ee68_2[13], o_44ee68_3[13], o_44ee68_4[13], o_44ee68_5[13], o_44ee68_6[13], o_44ee68_7[13];
static int32_t v_44eec8[44][3];
static ModelFace f_44eec8[12];
static int8_t o_44eec8_0[13], o_44eec8_1[13], o_44eec8_2[13], o_44eec8_3[13], o_44eec8_4[13], o_44eec8_5[13], o_44eec8_6[13], o_44eec8_7[13];
static int32_t v_44f058[4][3];
static ModelFace f_44f058[1];
static int32_t v_44f0a0[4][3];
static ModelFace f_44f0a0[1];
static int32_t v_44f188[4][3];
static ModelFace f_44f188[1];
static int32_t v_44f1d0[4][3];
static ModelFace f_44f1d0[1];
static int32_t v_44f298[4][3];
static ModelFace f_44f298[1];
static int32_t v_452dc8[4][3];
static ModelFace f_452dc8[1];
static int32_t v_452e0c[4][3];
static ModelFace f_452e0c[1];
static int32_t v_455680[50][3];
static ModelFace f_455680[15];
static int8_t o_455680_0[16], o_455680_1[16], o_455680_2[16], o_455680_3[16], o_455680_4[16], o_455680_5[16], o_455680_6[16], o_455680_7[16];
static int32_t v_455730[4][3];
static ModelFace f_455730[1];

typedef struct { int special, nv; int32_t (*v)[3]; int nf; ModelFace *f; int8_t *o[8]; uint8_t on[8]; } PartBuf;
static const uint32_t part_addr[MODEL_PART_COUNT] = {
    0x43f900, 0x43f998, 0x43fa30, 0x43fbb0, 0x441338, 0x4414f0, 0x441538, 0x4415b0,
    0x441698, 0x441840, 0x4418a0, 0x4419a0, 0x441a78, 0x441ac0, 0x441d68, 0x441db0,
    0x441df8, 0x441fa0, 0x442278, 0x4422c0, 0x442308, 0x4424b0, 0x4428a8, 0x4428ec,
    0x442d70, 0x442db4, 0x442e98, 0x442fd8, 0x443040, 0x4431f8, 0x4440a8, 0x4440f0,
    0x444178, 0x444200, 0x4443c8, 0x444490, 0x444588, 0x4445d0, 0x444698, 0x444780,
    0x4448e8, 0x4449d0, 0x444b38, 0x444cd0, 0x444d18, 0x444ed0, 0x444f18, 0x444f60,
    0x444fa8, 0x4450f8, 0x44513c, 0x445180, 0x4451c4, 0x445450, 0x445494, 0x4454d8,
    0x44551c, 0x4455e0, 0x445624, 0x445668, 0x4456ac, 0x445bb8, 0x445bfc, 0x445c40,
    0x445c84, 0x445cc8, 0x445d0c, 0x445d50, 0x445d98, 0x445ddc, 0x445e20, 0x445e64,
    0x445fa8, 0x446070, 0x4461d0, 0x446258, 0x4462c0, 0x446348, 0x446570, 0x446738,
    0x4467a0, 0x446998, 0x446a00, 0x446b08, 0x446c60, 0x446d28, 0x446e60, 0x446ea8,
    0x4470d0, 0x447118, 0x447160, 0x4471a8, 0x447230, 0x447278, 0x447908, 0x44794c,
    0x447990, 0x4479d4, 0x447a18, 0x447a5c, 0x447aa0, 0x447ae4, 0x447cb8, 0x447d00,
    0x447d68, 0x447dd0, 0x448268, 0x4482b0, 0x448708, 0x448750, 0x4487d8, 0x44881c,
    0x4488e0, 0x448924, 0x448968, 0x448df8, 0x448e40, 0x448e88, 0x448ef0, 0x4491c0,
    0x449208, 0x449270, 0x449318, 0x4493b0, 0x449478, 0x4495c0, 0x449628, 0x449730,
    0x449798, 0x4498a0, 0x449908, 0x4499a0, 0x449a08, 0x449aa0, 0x449ae8, 0x449d90,
    0x449dd8, 0x449e20, 0x449e68, 0x449eb0, 0x449ef8, 0x449f40, 0x449f88, 0x449fd0,
    0x44a2d8, 0x44a360, 0x44a3e8, 0x44a610, 0x44b000, 0x44c668, 0x44c6b0, 0x44c9b0,
    0x44ccb0, 0x44cd10, 0x44cdc0, 0x44ce48, 0x44ce90, 0x44cfe0, 0x44d3d0, 0x44d650,
    0x44d700, 0x44d788, 0x44d7d0, 0x44d920, 0x44dca8, 0x44dfb0, 0x44e070, 0x44e110,
    0x44e1a8, 0x44e240, 0x44e328, 0x44e3c0, 0x44e510, 0x44e610, 0x44e740, 0x44e9b8,
    0x44ea00, 0x44ee68, 0x44eec8, 0x44f058, 0x44f0a0, 0x44f188, 0x44f1d0, 0x44f298,
    0x452dc8, 0x452e0c, 0x455680, 0x455730,
};
static const PartBuf part_bufs[MODEL_PART_COUNT] = {
    [MP_43f900] = { 0, 8, v_43f900, 2, f_43f900, { NULL }, { 0 } },
    [MP_43f998] = { 0, 4, v_43f998, 1, f_43f998, { NULL }, { 0 } },
    [MP_43fa30] = { 0, 4, v_43fa30, 1, f_43fa30, { NULL }, { 0 } },
    [MP_43fbb0] = { 0, 4, v_43fbb0, 1, f_43fbb0, { NULL }, { 0 } },
    [MP_441338] = { 0, 4, v_441338, 1, f_441338, { NULL }, { 0 } },
    [MP_4414f0] = { 0, 8, v_4414f0, 5, f_4414f0, { NULL }, { 0 } },
    [MP_441538] = { 0, 8, v_441538, 5, f_441538, { NULL }, { 0 } },
    [MP_4415b0] = { 0, 4, v_4415b0, 1, f_4415b0, { NULL }, { 0 } },
    [MP_441698] = { 0, 8, v_441698, 5, f_441698, { NULL }, { 0 } },
    [MP_441840] = { 0, 12, v_441840, 5, f_441840, { o_441840_0, o_441840_1, o_441840_2, o_441840_3, o_441840_4, o_441840_5, o_441840_6, o_441840_7 }, { 4, 5, 5, 5, 5, 5, 4, 4 } },
    [MP_4418a0] = { 0, 12, v_4418a0, 5, f_4418a0, { o_4418a0_0, o_4418a0_1, o_4418a0_2, o_4418a0_3, o_4418a0_4, o_4418a0_5, o_4418a0_6, o_4418a0_7 }, { 4, 5, 5, 5, 5, 5, 4, 4 } },
    [MP_4419a0] = { 0, 12, v_4419a0, 5, f_4419a0, { NULL }, { 0 } },
    [MP_441a78] = { 0, 4, v_441a78, 1, f_441a78, { NULL }, { 0 } },
    [MP_441ac0] = { 0, 4, v_441ac0, 1, f_441ac0, { NULL }, { 0 } },
    [MP_441d68] = { 0, 8, v_441d68, 3, f_441d68, { NULL }, { 0 } },
    [MP_441db0] = { 0, 12, v_441db0, 4, f_441db0, { NULL }, { 0 } },
    [MP_441df8] = { 0, 12, v_441df8, 4, f_441df8, { NULL }, { 0 } },
    [MP_441fa0] = { 0, 16, v_441fa0, 5, f_441fa0, { NULL }, { 0 } },
    [MP_442278] = { 0, 8, v_442278, 3, f_442278, { NULL }, { 0 } },
    [MP_4422c0] = { 0, 12, v_4422c0, 4, f_4422c0, { NULL }, { 0 } },
    [MP_442308] = { 0, 12, v_442308, 4, f_442308, { NULL }, { 0 } },
    [MP_4424b0] = { 0, 16, v_4424b0, 5, f_4424b0, { NULL }, { 0 } },
    [MP_4428a8] = { 0, 15, v_4428a8, 7, f_4428a8, { NULL }, { 0 } },
    [MP_4428ec] = { 0, 15, v_4428ec, 7, f_4428ec, { NULL }, { 0 } },
    [MP_442d70] = { 0, 16, v_442d70, 8, f_442d70, { NULL }, { 0 } },
    [MP_442db4] = { 0, 16, v_442db4, 8, f_442db4, { NULL }, { 0 } },
    [MP_442e98] = { 0, 4, v_442e98, 1, f_442e98, { NULL }, { 0 } },
    [MP_442fd8] = { 0, 4, v_442fd8, 1, f_442fd8, { NULL }, { 0 } },
    [MP_443040] = { 0, 4, v_443040, 1, f_443040, { NULL }, { 0 } },
    [MP_4431f8] = { 0, 12, v_4431f8, 5, f_4431f8, { NULL }, { 0 } },
    [MP_4440a8] = { 0, 12, v_4440a8, 3, f_4440a8, { NULL }, { 0 } },
    [MP_4440f0] = { 0, 12, v_4440f0, 3, f_4440f0, { NULL }, { 0 } },
    [MP_444178] = { 0, 4, v_444178, 1, f_444178, { NULL }, { 0 } },
    [MP_444200] = { 0, 4, v_444200, 1, f_444200, { NULL }, { 0 } },
    [MP_4443c8] = { 0, 8, v_4443c8, 2, f_4443c8, { NULL }, { 0 } },
    [MP_444490] = { 0, 8, v_444490, 2, f_444490, { NULL }, { 0 } },
    [MP_444588] = { 0, 4, v_444588, 1, f_444588, { NULL }, { 0 } },
    [MP_4445d0] = { 0, 4, v_4445d0, 1, f_4445d0, { NULL }, { 0 } },
    [MP_444698] = { 0, 4, v_444698, 1, f_444698, { NULL }, { 0 } },
    [MP_444780] = { 0, 8, v_444780, 2, f_444780, { NULL }, { 0 } },
    [MP_4448e8] = { 0, 8, v_4448e8, 2, f_4448e8, { NULL }, { 0 } },
    [MP_4449d0] = { 0, 8, v_4449d0, 2, f_4449d0, { NULL }, { 0 } },
    [MP_444b38] = { 0, 8, v_444b38, 2, f_444b38, { NULL }, { 0 } },
    [MP_444cd0] = { 0, 4, v_444cd0, 1, f_444cd0, { NULL }, { 0 } },
    [MP_444d18] = { 0, 8, v_444d18, 3, f_444d18, { NULL }, { 0 } },
    [MP_444ed0] = { 0, 4, v_444ed0, 1, f_444ed0, { NULL }, { 0 } },
    [MP_444f18] = { 0, 4, v_444f18, 1, f_444f18, { NULL }, { 0 } },
    [MP_444f60] = { 0, 4, v_444f60, 1, f_444f60, { NULL }, { 0 } },
    [MP_444fa8] = { 0, 4, v_444fa8, 1, f_444fa8, { NULL }, { 0 } },
    [MP_4450f8] = { 0, 4, v_4450f8, 1, f_4450f8, { NULL }, { 0 } },
    [MP_44513c] = { 0, 4, v_44513c, 1, f_44513c, { NULL }, { 0 } },
    [MP_445180] = { 0, 4, v_445180, 1, f_445180, { NULL }, { 0 } },
    [MP_4451c4] = { 0, 4, v_4451c4, 1, f_4451c4, { NULL }, { 0 } },
    [MP_445450] = { 0, 12, v_445450, 5, f_445450, { NULL }, { 0 } },
    [MP_445494] = { 0, 12, v_445494, 5, f_445494, { NULL }, { 0 } },
    [MP_4454d8] = { 0, 12, v_4454d8, 5, f_4454d8, { NULL }, { 0 } },
    [MP_44551c] = { 0, 12, v_44551c, 5, f_44551c, { NULL }, { 0 } },
    [MP_4455e0] = { 0, 4, v_4455e0, 1, f_4455e0, { NULL }, { 0 } },
    [MP_445624] = { 0, 4, v_445624, 1, f_445624, { NULL }, { 0 } },
    [MP_445668] = { 0, 4, v_445668, 1, f_445668, { NULL }, { 0 } },
    [MP_4456ac] = { 0, 4, v_4456ac, 1, f_4456ac, { NULL }, { 0 } },
    [MP_445bb8] = { 0, 4, v_445bb8, 1, f_445bb8, { NULL }, { 0 } },
    [MP_445bfc] = { 0, 4, v_445bfc, 1, f_445bfc, { NULL }, { 0 } },
    [MP_445c40] = { 0, 4, v_445c40, 1, f_445c40, { NULL }, { 0 } },
    [MP_445c84] = { 0, 4, v_445c84, 1, f_445c84, { NULL }, { 0 } },
    [MP_445cc8] = { 0, 4, v_445cc8, 1, f_445cc8, { NULL }, { 0 } },
    [MP_445d0c] = { 0, 4, v_445d0c, 1, f_445d0c, { NULL }, { 0 } },
    [MP_445d50] = { 0, 4, v_445d50, 1, f_445d50, { NULL }, { 0 } },
    [MP_445d98] = { 0, 24, v_445d98, 10, f_445d98, { NULL }, { 0 } },
    [MP_445ddc] = { 0, 24, v_445ddc, 10, f_445ddc, { NULL }, { 0 } },
    [MP_445e20] = { 0, 24, v_445e20, 10, f_445e20, { NULL }, { 0 } },
    [MP_445e64] = { 0, 24, v_445e64, 10, f_445e64, { NULL }, { 0 } },
    [MP_445fa8] = { 0, 4, v_445fa8, 2, f_445fa8, { NULL }, { 0 } },
    [MP_446070] = { 0, 12, v_446070, 5, f_446070, { NULL }, { 0 } },
    [MP_4461d0] = { 0, 4, v_4461d0, 1, f_4461d0, { NULL }, { 0 } },
    [MP_446258] = { 0, 12, v_446258, 4, f_446258, { NULL }, { 0 } },
    [MP_4462c0] = { 0, 4, v_4462c0, 1, f_4462c0, { NULL }, { 0 } },
    [MP_446348] = { 0, 7, v_446348, 2, f_446348, { NULL }, { 0 } },
    [MP_446570] = { 0, 16, v_446570, 7, f_446570, { NULL }, { 0 } },
    [MP_446738] = { 0, 16, v_446738, 6, f_446738, { NULL }, { 0 } },
    [MP_4467a0] = { 0, 4, v_4467a0, 1, f_4467a0, { NULL }, { 0 } },
    [MP_446998] = { 0, 9, v_446998, 8, f_446998, { NULL }, { 0 } },
    [MP_446a00] = { 0, 4, v_446a00, 1, f_446a00, { NULL }, { 0 } },
    [MP_446b08] = { 0, 8, v_446b08, 4, f_446b08, { NULL }, { 0 } },
    [MP_446c60] = { 0, 4, v_446c60, 1, f_446c60, { NULL }, { 0 } },
    [MP_446d28] = { 0, 8, v_446d28, 4, f_446d28, { NULL }, { 0 } },
    [MP_446e60] = { 0, 4, v_446e60, 1, f_446e60, { NULL }, { 0 } },
    [MP_446ea8] = { 0, 4, v_446ea8, 1, f_446ea8, { NULL }, { 0 } },
    [MP_4470d0] = { 0, 4, v_4470d0, 1, f_4470d0, { NULL }, { 0 } },
    [MP_447118] = { 0, 4, v_447118, 1, f_447118, { NULL }, { 0 } },
    [MP_447160] = { 0, 4, v_447160, 1, f_447160, { NULL }, { 0 } },
    [MP_4471a8] = { 0, 4, v_4471a8, 1, f_4471a8, { NULL }, { 0 } },
    [MP_447230] = { 0, 4, v_447230, 1, f_447230, { NULL }, { 0 } },
    [MP_447278] = { 0, 4, v_447278, 1, f_447278, { NULL }, { 0 } },
    [MP_447908] = { 0, 8, v_447908, 5, f_447908, { NULL }, { 0 } },
    [MP_44794c] = { 0, 8, v_44794c, 5, f_44794c, { NULL }, { 0 } },
    [MP_447990] = { 0, 8, v_447990, 5, f_447990, { NULL }, { 0 } },
    [MP_4479d4] = { 0, 8, v_4479d4, 5, f_4479d4, { NULL }, { 0 } },
    [MP_447a18] = { 0, 8, v_447a18, 5, f_447a18, { NULL }, { 0 } },
    [MP_447a5c] = { 0, 8, v_447a5c, 5, f_447a5c, { NULL }, { 0 } },
    [MP_447aa0] = { 0, 8, v_447aa0, 5, f_447aa0, { NULL }, { 0 } },
    [MP_447ae4] = { 0, 8, v_447ae4, 5, f_447ae4, { NULL }, { 0 } },
    [MP_447cb8] = { 0, 4, v_447cb8, 1, f_447cb8, { NULL }, { 0 } },
    [MP_447d00] = { 0, 8, v_447d00, 5, f_447d00, { NULL }, { 0 } },
    [MP_447d68] = { 0, 4, v_447d68, 1, f_447d68, { NULL }, { 0 } },
    [MP_447dd0] = { 0, 4, v_447dd0, 1, f_447dd0, { NULL }, { 0 } },
    [MP_448268] = { 0, 28, v_448268, 11, f_448268, { NULL }, { 0 } },
    [MP_4482b0] = { 0, 28, v_4482b0, 11, f_4482b0, { NULL }, { 0 } },
    [MP_448708] = { 0, 28, v_448708, 11, f_448708, { NULL }, { 0 } },
    [MP_448750] = { 0, 28, v_448750, 11, f_448750, { NULL }, { 0 } },
    [MP_4487d8] = { 0, 4, v_4487d8, 1, f_4487d8, { NULL }, { 0 } },
    [MP_44881c] = { 0, 4, v_44881c, 1, f_44881c, { NULL }, { 0 } },
    [MP_4488e0] = { 0, 4, v_4488e0, 1, f_4488e0, { NULL }, { 0 } },
    [MP_448924] = { 0, 4, v_448924, 1, f_448924, { NULL }, { 0 } },
    [MP_448968] = { 0, 4, v_448968, 1, f_448968, { NULL }, { 0 } },
    [MP_448df8] = { 0, 18, v_448df8, 5, f_448df8, { NULL }, { 0 } },
    [MP_448e40] = { 0, 18, v_448e40, 5, f_448e40, { NULL }, { 0 } },
    [MP_448e88] = { 0, 18, v_448e88, 5, f_448e88, { NULL }, { 0 } },
    [MP_448ef0] = { 0, 4, v_448ef0, 1, f_448ef0, { NULL }, { 0 } },
    [MP_4491c0] = { 0, 11, v_4491c0, 4, f_4491c0, { NULL }, { 0 } },
    [MP_449208] = { 0, 11, v_449208, 4, f_449208, { NULL }, { 0 } },
    [MP_449270] = { 0, 4, v_449270, 1, f_449270, { NULL }, { 0 } },
    [MP_449318] = { 0, 4, v_449318, 1, f_449318, { NULL }, { 0 } },
    [MP_4493b0] = { 0, 4, v_4493b0, 1, f_4493b0, { NULL }, { 0 } },
    [MP_449478] = { 0, 4, v_449478, 1, f_449478, { NULL }, { 0 } },
    [MP_4495c0] = { 0, 8, v_4495c0, 3, f_4495c0, { NULL }, { 0 } },
    [MP_449628] = { 0, 4, v_449628, 1, f_449628, { NULL }, { 0 } },
    [MP_449730] = { 0, 8, v_449730, 3, f_449730, { NULL }, { 0 } },
    [MP_449798] = { 0, 4, v_449798, 1, f_449798, { NULL }, { 0 } },
    [MP_4498a0] = { 0, 8, v_4498a0, 3, f_4498a0, { NULL }, { 0 } },
    [MP_449908] = { 0, 4, v_449908, 1, f_449908, { NULL }, { 0 } },
    [MP_4499a0] = { 0, 4, v_4499a0, 1, f_4499a0, { NULL }, { 0 } },
    [MP_449a08] = { 0, 4, v_449a08, 1, f_449a08, { NULL }, { 0 } },
    [MP_449aa0] = { 0, 4, v_449aa0, 1, f_449aa0, { NULL }, { 0 } },
    [MP_449ae8] = { 0, 4, v_449ae8, 1, f_449ae8, { NULL }, { 0 } },
    [MP_449d90] = { 0, 4, v_449d90, 1, f_449d90, { NULL }, { 0 } },
    [MP_449dd8] = { 0, 4, v_449dd8, 1, f_449dd8, { NULL }, { 0 } },
    [MP_449e20] = { 0, 4, v_449e20, 1, f_449e20, { NULL }, { 0 } },
    [MP_449e68] = { 0, 4, v_449e68, 1, f_449e68, { NULL }, { 0 } },
    [MP_449eb0] = { 0, 4, v_449eb0, 1, f_449eb0, { NULL }, { 0 } },
    [MP_449ef8] = { 0, 4, v_449ef8, 1, f_449ef8, { NULL }, { 0 } },
    [MP_449f40] = { 0, 4, v_449f40, 1, f_449f40, { NULL }, { 0 } },
    [MP_449f88] = { 0, 4, v_449f88, 1, f_449f88, { NULL }, { 0 } },
    [MP_449fd0] = { 1, 0, NULL, 0, NULL, { NULL }, { 0 } },
    [MP_44a2d8] = { 0, 4, v_44a2d8, 1, f_44a2d8, { NULL }, { 0 } },
    [MP_44a360] = { 0, 12, v_44a360, 5, f_44a360, { NULL }, { 0 } },
    [MP_44a3e8] = { 0, 4, v_44a3e8, 2, f_44a3e8, { NULL }, { 0 } },
    [MP_44a610] = { 0, 16, v_44a610, 9, f_44a610, { NULL }, { 0 } },
    [MP_44b000] = { 0, 4, v_44b000, 1, f_44b000, { NULL }, { 0 } },
    [MP_44c668] = { 0, 4, v_44c668, 1, f_44c668, { NULL }, { 0 } },
    [MP_44c6b0] = { 0, 4, v_44c6b0, 2, f_44c6b0, { NULL }, { 0 } },
    [MP_44c9b0] = { 0, 4, v_44c9b0, 1, f_44c9b0, { NULL }, { 0 } },
    [MP_44ccb0] = { 0, 22, v_44ccb0, 8, f_44ccb0, { o_44ccb0_0, o_44ccb0_1, o_44ccb0_2, o_44ccb0_3, o_44ccb0_4, o_44ccb0_5, o_44ccb0_6, o_44ccb0_7 }, { 8, 8, 8, 8, 8, 8, 8, 8 } },
    [MP_44cd10] = { 0, 24, v_44cd10, 6, f_44cd10, { o_44cd10_0, o_44cd10_1, o_44cd10_2, o_44cd10_3, o_44cd10_4, o_44cd10_5, o_44cd10_6, o_44cd10_7 }, { 6, 6, 6, 6, 6, 6, 6, 6 } },
    [MP_44cdc0] = { 0, 4, v_44cdc0, 1, f_44cdc0, { NULL }, { 0 } },
    [MP_44ce48] = { 0, 8, v_44ce48, 2, f_44ce48, { NULL }, { 0 } },
    [MP_44ce90] = { 0, 24, v_44ce90, 6, f_44ce90, { o_44ce90_0, o_44ce90_1, o_44ce90_2, o_44ce90_3, o_44ce90_4, o_44ce90_5, o_44ce90_6, o_44ce90_7 }, { 6, 6, 6, 6, 6, 6, 6, 6 } },
    [MP_44cfe0] = { 0, 12, v_44cfe0, 3, f_44cfe0, { NULL }, { 0 } },
    [MP_44d3d0] = { 0, 4, v_44d3d0, 1, f_44d3d0, { NULL }, { 0 } },
    [MP_44d650] = { 0, 52, v_44d650, 14, f_44d650, { o_44d650_0, o_44d650_1, o_44d650_2, o_44d650_3, o_44d650_4, o_44d650_5, o_44d650_6, o_44d650_7 }, { 14, 14, 14, 14, 14, 14, 14, 14 } },
    [MP_44d700] = { 0, 4, v_44d700, 1, f_44d700, { NULL }, { 0 } },
    [MP_44d788] = { 0, 8, v_44d788, 2, f_44d788, { NULL }, { 0 } },
    [MP_44d7d0] = { 0, 52, v_44d7d0, 14, f_44d7d0, { o_44d7d0_0, o_44d7d0_1, o_44d7d0_2, o_44d7d0_3, o_44d7d0_4, o_44d7d0_5, o_44d7d0_6, o_44d7d0_7 }, { 14, 14, 14, 14, 14, 14, 14, 14 } },
    [MP_44d920] = { 0, 12, v_44d920, 3, f_44d920, { NULL }, { 0 } },
    [MP_44dca8] = { 0, 4, v_44dca8, 1, f_44dca8, { NULL }, { 0 } },
    [MP_44dfb0] = { 0, 48, v_44dfb0, 12, f_44dfb0, { o_44dfb0_0, o_44dfb0_1, o_44dfb0_2, o_44dfb0_3, o_44dfb0_4, o_44dfb0_5, o_44dfb0_6, o_44dfb0_7 }, { 12, 12, 12, 12, 12, 12, 12, 12 } },
    [MP_44e070] = { 0, 44, v_44e070, 11, f_44e070, { o_44e070_0, o_44e070_1, o_44e070_2, o_44e070_3, o_44e070_4, o_44e070_5, o_44e070_6, o_44e070_7 }, { 11, 11, 11, 11, 11, 11, 11, 11 } },
    [MP_44e110] = { 0, 6, v_44e110, 2, f_44e110, { NULL }, { 0 } },
    [MP_44e1a8] = { 0, 4, v_44e1a8, 1, f_44e1a8, { NULL }, { 0 } },
    [MP_44e240] = { 0, 4, v_44e240, 1, f_44e240, { NULL }, { 0 } },
    [MP_44e328] = { 0, 8, v_44e328, 2, f_44e328, { NULL }, { 0 } },
    [MP_44e3c0] = { 0, 36, v_44e3c0, 9, f_44e3c0, { o_44e3c0_0, o_44e3c0_1, o_44e3c0_2, o_44e3c0_3, o_44e3c0_4, o_44e3c0_5, o_44e3c0_6, o_44e3c0_7 }, { 9, 9, 9, 9, 9, 9, 9, 9 } },
    [MP_44e510] = { 0, 12, v_44e510, 3, f_44e510, { NULL }, { 0 } },
    [MP_44e610] = { 0, 8, v_44e610, 2, f_44e610, { NULL }, { 0 } },
    [MP_44e740] = { 0, 8, v_44e740, 2, f_44e740, { NULL }, { 0 } },
    [MP_44e9b8] = { 0, 4, v_44e9b8, 1, f_44e9b8, { NULL }, { 0 } },
    [MP_44ea00] = { 0, 6, v_44ea00, 2, f_44ea00, { NULL }, { 0 } },
    [MP_44ee68] = { 0, 44, v_44ee68, 12, f_44ee68, { o_44ee68_0, o_44ee68_1, o_44ee68_2, o_44ee68_3, o_44ee68_4, o_44ee68_5, o_44ee68_6, o_44ee68_7 }, { 12, 12, 12, 12, 12, 12, 12, 12 } },
    [MP_44eec8] = { 0, 44, v_44eec8, 12, f_44eec8, { o_44eec8_0, o_44eec8_1, o_44eec8_2, o_44eec8_3, o_44eec8_4, o_44eec8_5, o_44eec8_6, o_44eec8_7 }, { 12, 12, 12, 12, 12, 12, 12, 12 } },
    [MP_44f058] = { 0, 4, v_44f058, 1, f_44f058, { NULL }, { 0 } },
    [MP_44f0a0] = { 0, 4, v_44f0a0, 1, f_44f0a0, { NULL }, { 0 } },
    [MP_44f188] = { 0, 4, v_44f188, 1, f_44f188, { NULL }, { 0 } },
    [MP_44f1d0] = { 0, 4, v_44f1d0, 1, f_44f1d0, { NULL }, { 0 } },
    [MP_44f298] = { 0, 4, v_44f298, 1, f_44f298, { NULL }, { 0 } },
    [MP_452dc8] = { 0, 4, v_452dc8, 1, f_452dc8, { NULL }, { 0 } },
    [MP_452e0c] = { 0, 4, v_452e0c, 1, f_452e0c, { NULL }, { 0 } },
    [MP_455680] = { 0, 50, v_455680, 15, f_455680, { o_455680_0, o_455680_1, o_455680_2, o_455680_3, o_455680_4, o_455680_5, o_455680_6, o_455680_7 }, { 15, 15, 15, 15, 15, 15, 15, 15 } },
    [MP_455730] = { 0, 4, v_455730, 1, f_455730, { NULL }, { 0 } },
};

/* ---- loader: fills the structures above from the RFIRE.BIN image (layout: docs/render.md 5/7) ---- */
static ModelPart *part_at(uint32_t a)
{
    int lo = 0, hi = MODEL_PART_COUNT - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (part_addr[mid] == a) return &model_parts[mid];
        if (part_addr[mid] < a) lo = mid + 1; else hi = mid - 1;
    }
    return NULL;
}

static void models_load(void)
{
    for (int i = 0; i < MODEL_PART_COUNT; i++) {
        const PartBuf *b = &part_bufs[i];
        ModelPart *m = &model_parts[i];
        uint32_t a = part_addr[i];
        memset(m, 0, sizeof *m);
        m->addr = a;
        m->fn = exe_u32(a);
        m->next = part_at(exe_u32(a + 4));
        m->shape = exe_u32(a + 8);
        m->size = exe_s32(a + 0xc);
        m->flags = exe_u32(a + 0x10);
        for (int k = 0; k < 3; k++) m->off[k] = exe_s32(a + 0x14 + 4 * k);
        m->zbias = exe_s32(a + 0x20);
        m->depth_hook = exe_u32(a + 0x24);
        m->pos_hook = exe_u32(a + 0x28);
        if (b->special) { m->special = 1; continue; }
        uint32_t vp = exe_u32(a + 0x30), fp = exe_u32(a + 0x38);
        for (int v = 0; v < b->nv; v++)
            for (int k = 0; k < 3; k++) b->v[v][k] = exe_s32(vp + 12 * v + 4 * k);
        m->nverts = b->nv;
        m->verts = b->v;
        m->nfaces_field = exe_s32(a + 0x34);
        for (int f = 0; f < b->nf; f++) {
            uint32_t q = fp + 32 * f;
            b->f[f] = (ModelFace){ exe_s32(q), exe_u32(q + 4), (int8_t)exe_s32(q + 8), (int8_t)exe_s32(q + 12),
                                   { (uint8_t)exe_s32(q + 16), (uint8_t)exe_s32(q + 20), (uint8_t)exe_s32(q + 24),
                                     (uint8_t)exe_s32(q + 28) } };
        }
        m->nfaces = b->nf;
        m->faces = b->f;
        for (int k = 0; k < 8 && b->o[k]; k++) {         /* per-yaw face lists: bytes ending with a negative one */
            uint32_t p = exe_u32(a + 0x3c + 4 * k);
            for (int j = 0; j < b->on[k]; j++) b->o[k][j] = exe_s8(p + j);
            b->o[k][b->on[k]] = -1;
            m->orders[k] = b->o[k];
        }
    }
    for (int i = 0; i < RENDER_BNO_COUNT; i++) {         /* BNO table 0x451438, stride 0x38 */
        uint32_t b = 0x451438 + 0x38 * (uint32_t)i;
        RenderBno *r = &render_bno[i];
        r->name = exe_str(exe_u32(b + 4));
        r->model_addr = exe_u32(b + 8);
        r->model = part_at(r->model_addr);
        r->flags = exe_u32(b + 0xc);
        r->terrain = exe_u8(b + 0x10);
        r->strength = exe_u8(b + 0x11);
    }
    for (int i = 0; i < 12; i++) {                       /* projectile table 0x450a78 (stride 0x3c) +0x2c / +0x30 */
        model_projectile_model[i] = part_at(exe_u32(0x450a78 + 0x3c * (uint32_t)i + 0x2c));
        model_projectile_shadow[i] = part_at(exe_u32(0x450a78 + 0x3c * (uint32_t)i + 0x30));
    }
}
EXE_LOADER(models_load)
