#!/usr/bin/env python3
"""Generate src/game/rules_tables.c: the layout of the collision shapes, graphic descriptors and tunables of
the MAN (0x43fb10), Gate (0x44ade0) and Flag (0x44ae30) classes in RFIRE.BIN, plus the loader that fills the
C structures from the user's RFIRE.BIN at start-up (exe.c). No data from the executable is emitted; it is
only needed to regenerate the file (to discover the shape chains).

Usage: python3 tools/gen_rules_tables.py [path/to/RFIRE.BIN] > src/game/rules_tables.c
Kept apart from gen_game_tables.py so the two generators can evolve independently. See docs/game.md §10.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rfexe  # noqa: E402

pe = rfexe.Exe(sys.argv[1] if len(sys.argv) > 1 else None)
u32, s32 = pe.u32, pe.s32

# ---- shape parts (AABBs only; asserted) ----
parts = []


def add_chain(p):
    while p and p not in parts:
        parts.append(p)
        assert s32(p) == 2, hex(p)
        p = u32(p + 4)


for p in (0x43f8c0, 0x43f880, 0x44e6f8, 0x442930, 0x442df8, 0x4424f8):
    add_chain(p)
GFX = [(0x43f900, 'MAN walking (Model_DrawMan 0x4061c0)'), (0x43f998, 'MAN swimming (0x406280)'),
       (0x43fa30, 'dead man (Stay, Model_DrawStatic)'), (0x44e740, 'Flag on the ground (0x42f740)'),
       (0x44e610, 'Flag carried by a jeep (0x42f6e0)')]
for g, _ in GFX:
    assert u32(g + 8) == 0 or u32(g + 8) in parts, hex(g)
GATES = (0x4428a8, 0x442d70)      # gate templates: the shape is replaced by the door parts (+0x88)
for g in GATES:
    assert g + 0x88 in parts

out = []
P = out.append
P('/* Generated by tools/gen_rules_tables.py from the layout of RFIRE.BIN. Do not edit.')
P('   Shapes, graphics and tunables of the MAN (0x43fb10), Gate (0x44ade0) and Flag (0x44ae30) classes.')
P('   Addresses only: the contents are read from the user\'s RFIRE.BIN at start-up (exe.c, rules_tables_load). */')
P('#include <stddef.h>')
P('#include "rules.h"')
P('#include "../exe.h"')
P('')
for p in parts:
    P('static ShapePart rshp_%x;' % p)
P('static ShapePart *const rshp_descs[%d] = { %s };' % (len(parts), ', '.join('&rshp_%x' % p for p in parts)))
P('static const uint32_t rshp_addrs[%d] = { %s };' % (len(parts), ', '.join('0x%x' % p for p in parts)))
P('')
P('/* gate door parts (heap copies are made per Gate object by GateInit 0x423cd0) */')
P('const ShapePart *const gate_door_parts[2] = { &rshp_442930, &rshp_442df8 };   /* H (0x4428a8+0x88), V (0x442d70+0x88) */')
P('ShapePart *const gate_zone_part = &rshp_4424f8;   /* the pickup zone of BNO 43/44 (GateUpdate: parent still near) */')
P('')
for g, what in GFX:
    P('Gfx rgfx_%x;   /* %s */' % (g, what))
for g in GATES:
    P('Gfx rgfx_%x;   /* Gate (copy of the graphic, door parts) */' % g)
P('')
P('/* MAN tunables */')
P('int32_t man_walk_speed;          /* DAT_0043fa74 px/tick */')
P('int32_t man_anim_rate;           /* DAT_0043fa7c frames/tick */')
P('int32_t man_grenade_min;         /* DAT_0043fa98 min distance for a grenade */')
P('int8_t man_grenades[16];         /* DAT_0043fa88 by RandRange(16) */')
P('int32_t man_unstick[8][3];       /* DAT_0043fab0 */')
P('int32_t flag_carry_offset[3];    /* DAT_0044e558 (rotated by the jeep heading) */')
P('int32_t flag_pitch_bias, flag_pitch_shift;   /* DAT_0044e734 / DAT_0044e738 */')
P('int32_t win_movie_by_level[10];  /* DAT_004559e0 */')
P('int32_t win_banner_pos[4][2];    /* DAT_00455a18 (x, y; -1 = centred; doubled in 640x480) */')
P(r'''
static ShapePart *rshp_at(uint32_t va)
{
    for (int i = 0; va && i < (int)(sizeof rshp_addrs / sizeof *rshp_addrs); i++)
        if (rshp_addrs[i] == va) return rshp_descs[i];
    return NULL;
}

static void rd_s32(int32_t *dst, uint32_t va, int n) { for (int i = 0; i < n; i++) dst[i] = exe_s32(va + 4 * (uint32_t)i); }

static void rules_tables_load(void)
{
    for (int i = 0; i < (int)(sizeof rshp_addrs / sizeof *rshp_addrs); i++) {    /* type 2 (AABB) parts */
        uint32_t p = rshp_addrs[i];
        ShapePart *s = rshp_descs[i];
        *s = (ShapePart){ 0 };
        s->type = exe_s32(p);
        s->next = rshp_at(exe_u32(p + 4));
        s->b8 = exe_u8(p + 8); s->kind = exe_u8(p + 9); s->solid = exe_u8(p + 10); s->mask = exe_u8(p + 11);
        s->zlo = exe_s32(p + 0xc); s->zhi = exe_s32(p + 0x10);
        s->dx = exe_s32(p + 0x14); s->dy = exe_s32(p + 0x18);
        rd_s32(s->bbox, p + 0x1c, 4);
        s->addr = p;
    }
    Gfx *const g[] = { %s };
    const uint32_t ga[] = { %s };
    for (size_t i = 0; i < sizeof g / sizeof *g; i++)
        *g[i] = (Gfx){ ga[i], rshp_at(exe_u32(ga[i] + 8)), exe_s32(ga[i] + 12), GADJ_NONE };
    Gfx *const gates[] = { %s };
    const uint32_t gta[] = { %s };
    for (size_t i = 0; i < sizeof gates / sizeof *gates; i++)
        *gates[i] = (Gfx){ gta[i], rshp_at(gta[i] + 0x88), exe_s32(gta[i] + 12), GADJ_NONE };
    man_walk_speed = exe_s32(0x43fa74);
    man_anim_rate = exe_s32(0x43fa7c);
    man_grenade_min = exe_s32(0x43fa98);
    for (int i = 0; i < 16; i++) man_grenades[i] = exe_s8(0x43fa88 + (uint32_t)i);
    rd_s32(&man_unstick[0][0], 0x43fab0, 24);
    rd_s32(flag_carry_offset, 0x44e558, 3);
    flag_pitch_bias = exe_s32(0x44e734); flag_pitch_shift = exe_s32(0x44e738);
    rd_s32(win_movie_by_level, 0x4559e0, 10);
    rd_s32(&win_banner_pos[0][0], 0x455a18, 8);
}
EXE_LOADER(rules_tables_load)''' % (', '.join('&rgfx_%x' % g for g, _ in GFX), ', '.join('0x%x' % g for g, _ in GFX),
       ', '.join('&rgfx_%x' % g for g in GATES), ', '.join('0x%x' % g for g in GATES)))
print('\n'.join(out))
