#!/usr/bin/env python3
"""Generate src/world_tables.c: loader of the RFM tile table (RFIRE.BIN 0x452858, 240 x {terrain, object,
team, handler}) and the map-object fields of the BNO table (0x451438, 91 x 0x38: +0x04 name, +0x10 terrain
override, +0x11 strength, +0x34 radar colours). The generated file holds addresses and counts only; the
contents are read from the user's RFIRE.BIN at start-up (exe.c). See docs/rfm.md.

Usage: python3 tools/gen_world_tables.py > src/world_tables.c   (no executable needed)
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rfexe  # noqa: E402

sys.stdout.write(r'''/* Generated by tools/gen_world_tables.py. Do not edit.
   RFM tile table (RFIRE.BIN 0x%(tt)x) and BNO map-object fields (0x%(bt)x, stride 0x%(bs)x), read from the
   user's RFIRE.BIN at start-up (exe.c). */
#include "world.h"
#include "exe.h"

TileDef tile_table[%(tn)d];
ObjDef obj_table[OBJ_COUNT];

static void world_tables_load(void)
{
    for (int i = 0; i < %(tn)d; i++) {
        uint32_t a = 0x%(tt)x + 4 * (uint32_t)i;
        tile_table[i] = (TileDef){ exe_u8(a), exe_u8(a + 1), exe_u8(a + 2), exe_u8(a + 3) };
    }
    for (int i = 0; i < OBJ_COUNT; i++) {
        uint32_t b = 0x%(bt)x + 0x%(bs)x * (uint32_t)i;
        obj_table[i] = (ObjDef){ exe_str(exe_u32(b + 4)), exe_u8(b + 0x10), exe_u8(b + 0x11), exe_u32(b + 0x34) };
    }
}
EXE_LOADER(world_tables_load)
''' % dict(tt=rfexe.TILE_TABLE_VA, tn=rfexe.TILE_COUNT, bt=rfexe.BNO_TABLE_VA, bs=rfexe.BNO_STRIDE))
