#!/usr/bin/env python3
"""Generate src/render/models_data.c + src/render/models_data.h: the layout of every 3D model part in
RFIRE.BIN .data (addresses, vertex / face / face-order counts), the BNO -> model table and the projectile
model tables, plus the loader that fills the C structures from the user's RFIRE.BIN at start-up (exe.c).

The generated files contain no data from the executable, only addresses, counts and types; the executable
is needed to regenerate them (the counts are discovered with tools/models.py), not to build.

Usage: python3 tools/gen_models_c.py [path/to/RFIRE.BIN] [src/render]
Output is deterministic (parts sorted by address).
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import models as M   # noqa: E402


def ident(s):
    s = re.sub(r'\(.*?\)', '', s)
    s = re.sub(r'[^A-Za-z0-9]+', '_', s).strip('_').upper()
    return s


LOADER = r'''
/* ---- loader: fills the structures above from the RFIRE.BIN image (layout: docs/render.md 5/7) ---- */
static ModelPart *part_at(uint32_t a)
{
    int lo = 0, hi = MODEL_PART_COUNT - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (part_addr[mid] == a) return &model_parts[mid];
        if (part_addr[mid] < a) lo = mid + 1; else hi = mid - 1;
    }
    return NULL;
}

static void models_load(void)
{
    for (int i = 0; i < MODEL_PART_COUNT; i++) {
        const PartBuf *b = &part_bufs[i];
        ModelPart *m = &model_parts[i];
        uint32_t a = part_addr[i];
        memset(m, 0, sizeof *m);
        m->addr = a;
        m->fn = exe_u32(a);
        m->next = part_at(exe_u32(a + 4));
        m->shape = exe_u32(a + 8);
        m->size = exe_s32(a + 0xc);
        m->flags = exe_u32(a + 0x10);
        for (int k = 0; k < 3; k++) m->off[k] = exe_s32(a + 0x14 + 4 * k);
        m->zbias = exe_s32(a + 0x20);
        m->depth_hook = exe_u32(a + 0x24);
        m->pos_hook = exe_u32(a + 0x28);
        if (b->special) { m->special = 1; continue; }
        uint32_t vp = exe_u32(a + 0x30), fp = exe_u32(a + 0x38);
        for (int v = 0; v < b->nv; v++)
            for (int k = 0; k < 3; k++) b->v[v][k] = exe_s32(vp + 12 * v + 4 * k);
        m->nverts = b->nv;
        m->verts = b->v;
        m->nfaces_field = exe_s32(a + 0x34);
        for (int f = 0; f < b->nf; f++) {
            uint32_t q = fp + 32 * f;
            b->f[f] = (ModelFace){ exe_s32(q), exe_u32(q + 4), (int8_t)exe_s32(q + 8), (int8_t)exe_s32(q + 12),
                                   { (uint8_t)exe_s32(q + 16), (uint8_t)exe_s32(q + 20), (uint8_t)exe_s32(q + 24),
                                     (uint8_t)exe_s32(q + 28) } };
        }
        m->nfaces = b->nf;
        m->faces = b->f;
        for (int k = 0; k < 8 && b->o[k]; k++) {         /* per-yaw face lists: bytes ending with a negative one */
            uint32_t p = exe_u32(a + 0x3c + 4 * k);
            for (int j = 0; j < b->on[k]; j++) b->o[k][j] = exe_s8(p + j);
            b->o[k][b->on[k]] = -1;
            m->orders[k] = b->o[k];
        }
    }
    for (int i = 0; i < RENDER_BNO_COUNT; i++) {         /* BNO table 0x451438, stride 0x38 */
        uint32_t b = 0x451438 + 0x38 * (uint32_t)i;
        RenderBno *r = &render_bno[i];
        r->name = exe_str(exe_u32(b + 4));
        r->model_addr = exe_u32(b + 8);
        r->model = part_at(r->model_addr);
        r->flags = exe_u32(b + 0xc);
        r->terrain = exe_u8(b + 0x10);
        r->strength = exe_u8(b + 0x11);
    }
    for (int i = 0; i < 12; i++) {                       /* projectile table 0x450a78 (stride 0x3c) +0x2c / +0x30 */
        model_projectile_model[i] = part_at(exe_u32(0x450a78 + 0x3c * (uint32_t)i + 0x2c));
        model_projectile_shadow[i] = part_at(exe_u32(0x450a78 + 0x3c * (uint32_t)i + 0x30));
    }
}
EXE_LOADER(models_load)
'''


def main():
    exe = sys.argv[1] if len(sys.argv) > 1 else None
    dst = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, 'src/render')
    pe, models = M.load(exe)
    use = M.users(pe, models)
    addrs = sorted(models)

    c = []
    P = c.append
    P('/* Generated by tools/gen_models_c.py from the layout of RFIRE.BIN. Do not edit.')
    P('   All 3D model parts of RFIRE.BIN .data (see docs/render.md section 7): addresses and counts only;')
    P('   the geometry is read from the user\'s RFIRE.BIN at start-up (exe.c, models_load below). */')
    P('#include "model.h"')
    P('#include "../exe.h"')
    P('#include <string.h>')
    P('')
    P('ModelPart model_parts[MODEL_PART_COUNT];')
    P('RenderBno render_bno[RENDER_BNO_COUNT];')
    P('const ModelPart *model_projectile_model[12];')
    P('const ModelPart *model_projectile_shadow[12];')
    P('')
    P('/* vertex / face / face-order buffers (part address; counts from the part header +0x2c / +0x34) */')
    for a in addrs:
        m = models[a]
        if m.special:
            continue
        P('static int32_t v_%06x[%d][3];' % (a, len(m.verts)))
        P('static ModelFace f_%06x[%d];' % (a, len(m.faces)))
        if m.orders is not None:
            P('static int8_t %s;' % ', '.join('o_%06x_%d[%d]' % (a, k, len(o) + 1) for k, o in enumerate(m.orders)))
    P('')
    P('typedef struct { int special, nv; int32_t (*v)[3]; int nf; ModelFace *f; int8_t *o[8]; uint8_t on[8]; } PartBuf;')
    P('static const uint32_t part_addr[MODEL_PART_COUNT] = {')
    for k in range(0, len(addrs), 8):
        P('    ' + ', '.join('0x%06x' % a for a in addrs[k:k + 8]) + ',')
    P('};')
    P('static const PartBuf part_bufs[MODEL_PART_COUNT] = {')
    for a in addrs:
        m = models[a]
        if m.special:
            P('    [MP_%06x] = { 1, 0, NULL, 0, NULL, { NULL }, { 0 } },' % a)
            continue
        if m.orders is not None:
            o = '{ %s }, { %s }' % (', '.join('o_%06x_%d' % (a, k) for k in range(8)),
                                    ', '.join(str(len(x)) for x in m.orders))
        else:
            o = '{ NULL }, { 0 }'
        P('    [MP_%06x] = { 0, %d, v_%06x, %d, f_%06x, %s },' % (a, len(m.verts), a, len(m.faces), a, o))
    P('};')
    c.append(LOADER.rstrip('\n'))
    open(os.path.join(dst, 'models_data.c'), 'w').write('\n'.join(c) + '\n')

    h = []
    P = h.append
    P('/* Generated by tools/gen_models_c.py from the layout of RFIRE.BIN. Do not edit. */')
    P('#pragma once')
    P('')
    P('enum {')
    for i, a in enumerate(addrs):
        P('    MP_%06x = %d,' % (a, i))
    P('    MODEL_PART_COUNT = %d' % len(addrs))
    P('};')
    P('')
    P('/* Named model parts (class descriptor +0x14, vehicle def fields, code references). */')
    names = {}
    for a in addrs:
        for u in use[a]:
            n = None
            r = re.match(r'class (.*) \(0x([0-9a-f]+)\+0x14\)', u)
            if r:
                n = 'MODEL_CLASS_' + ident(r.group(1))
                if 'large' in r.group(1):
                    n += '_LARGE'
                elif 'rising' in r.group(1):
                    n += '_RISING'
                elif 'lowering' in r.group(1):
                    n += '_LOWERING'
            r = re.match(r'vehicle (\w+) def\[0x([0-9a-f]+)\] (.*)', u)
            if r:
                n = 'MODEL_%s_%s' % (ident(r.group(1)), ident(r.group(3)))
            r = re.match(r'code: (.*)', u)
            if r:
                n = 'MODEL_' + ident(r.group(1))
            if n:
                base, k = n, 2
                while n in names and names[n] != a:
                    n = '%s_%d' % (base, k)
                    k += 1
                names[n] = a
    for n in sorted(names):
        P('#define %-36s (&model_parts[MP_%06x])' % (n, names[n]))
    open(os.path.join(dst, 'models_data.h'), 'w').write('\n'.join(h) + '\n')
    print('%d parts, %d names -> %s' % (len(addrs), len(names), dst))


if __name__ == '__main__':
    main()
