#!/usr/bin/env python3
"""Generate src/sfx_tables.c: the layout of the sound-effect tables of RFIRE.BIN (base 0x400000) plus the loader
that fills sfx_samples / sfx_events / sfx_event_list / sfx_step_events from the user's RFIRE.BIN at start-up
(exe.c). No data from the executable is emitted (the table bounds below are addresses and counts only); the
executable is only used to check the layout when regenerating.

Usage: python3 tools/gen_sfx_tables.py [path/to/RFIRE.BIN] > src/sfx_tables.c

Tables (docs/architecture.md section 7):
  0x43e550  sample table, 37 x 0x1c: path, flags, SampleRec*, -, rate field, marker list*, index
  0x43e960  sound-event table, 0x18 per entry up to and including 0x43edc8 (48 entries; the
            first one, "tread", precedes the 0x43e978 "jeep" entry the docs start from)
  0x43ede0  event pointer list (index -> event, used by byte scripts and the debug editor);
            0x43ee2c = entry 19 = the three "Throw Grenade" variants picked with RandRange(3)
  0x43f278  bunker lift sound-step events (FUN_004042b0): PreRaise, Raise
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rfexe  # noqa: E402

pe = rfexe.Exe(sys.argv[1] if len(sys.argv) > 1 else None)
u32 = pe.u32

SAMPLES, NSAMP, SSTRIDE = 0x43e550, 37, 0x1c
EVENTS, EV_END, ESTRIDE = 0x43e960, 0x43edc8, 0x18
LIST, LIST_END = 0x43ede0, 0x43ee90
STEPS = 0x43f278
CALLBACKS = {0: 'SFX_CB_NONE', 0x42b960: 'SFX_CB_ENGINE', 0x42b9b0: 'SFX_CB_ROTOR'}

# layout checks (the loader re-checks them at run time)
for i in range(NSAMP):
    a = SAMPLES + i * SSTRIDE
    assert u32(a + 24) == i and u32(a + 16) == 0
nev = (EV_END - EVENTS) // ESTRIDE + 1
assert nev == 48
for i in range(nev):
    a = EVENTS + i * ESTRIDE
    si = (u32(a + 4) - SAMPLES) // SSTRIDE
    assert u32(a + 4) == SAMPLES + si * SSTRIDE and 0 <= si < NSAMP and u32(a + 20) in CALLBACKS
nlist = (LIST_END - LIST) // 4
assert nlist == 44
for a in list(range(LIST, LIST_END, 4)) + [STEPS, STEPS + 4]:
    assert (u32(a) - EVENTS) % ESTRIDE == 0

src = r'''/* Generated by tools/gen_sfx_tables.py from the layout of RFIRE.BIN. Do not edit.
   Sample table 0x43e550, sound-event table 0x43e960..0x43edc8, event list 0x43ede0,
   bunker lift sound steps 0x43f278 (docs/architecture.md section 7). Addresses only: the contents are
   read from the user's RFIRE.BIN at start-up (exe.c, sfx_tables_load below). */
#include "sfx.h"
#include "exe.h"
#include <stdio.h>
#include <stdlib.h>

SfxSample sfx_samples[SFX_NSAMPLES];
SfxEvent sfx_events[SFX_NEVENTS];
uint8_t sfx_event_list[SFX_NLIST];
uint8_t sfx_step_events[2];

enum { SAMPLES = 0x%(SAMPLES)x, SSTRIDE = 0x%(SSTRIDE)x, LIST = 0x%(LIST)x, STEPS = 0x%(STEPS)x };
static const uint32_t callbacks[3] = { 0, 0x42b960, 0x42b9b0 };   /* SFX_CB_NONE, _ENGINE, _ROTOR */

static void fail(const char *what, uint32_t va)
{
    fprintf(stderr, "sfx_tables: unexpected %%s at 0x%%x in RFIRE.BIN\n", what, va);
    abort();
}

static uint8_t event_index(uint32_t va)
{
    uint32_t k = (va - SFX_EVENT_BASE) / SFX_EVENT_STRIDE;
    if (va < SFX_EVENT_BASE || k >= SFX_NEVENTS || va != SFX_EVENT_BASE + k * SFX_EVENT_STRIDE) fail("event pointer", va);
    return (uint8_t)k;
}

static void sfx_tables_load(void)
{
    for (int i = 0; i < SFX_NSAMPLES; i++) {
        uint32_t a = SAMPLES + SSTRIDE * (uint32_t)i, mk = exe_u32(a + 20);
        int32_t ls = -1, le = -1;
        for (uint32_t k = mk; mk && exe_u32(k); k += 8) {        /* marker list {tag, value}, 0-terminated */
            if (exe_u32(k) == 0x1f) ls = exe_s32(k + 4);
            else if (exe_u32(k) == 0x20) le = exe_s32(k + 4);
        }
        sfx_samples[i] = (SfxSample){ exe_str(exe_u32(a)), exe_u32(a + 4), ls, le };
    }
    for (int i = 0; i < SFX_NEVENTS; i++) {
        uint32_t a = SFX_EVENT_BASE + SFX_EVENT_STRIDE * (uint32_t)i, samp = exe_u32(a + 4), cb = exe_u32(a + 20);
        uint32_t si = (samp - SAMPLES) / SSTRIDE;
        if (samp < SAMPLES || si >= SFX_NSAMPLES || samp != SAMPLES + si * SSTRIDE) fail("sample pointer", a);
        uint8_t c = cb == callbacks[1] ? SFX_CB_ENGINE : cb == callbacks[2] ? SFX_CB_ROTOR : SFX_CB_NONE;
        if (cb != callbacks[c]) fail("callback", a);
        sfx_events[i] = (SfxEvent){ a, exe_str(exe_u32(a)), (uint8_t)si, exe_u8(a + 8), exe_u8(a + 9), exe_u8(a + 10),
                                    exe_u8(a + 11), exe_s32(a + 12), exe_s32(a + 16), c };
    }
    for (int i = 0; i < SFX_NLIST; i++) sfx_event_list[i] = event_index(exe_u32(LIST + 4 * (uint32_t)i));
    for (int i = 0; i < 2; i++) sfx_step_events[i] = event_index(exe_u32(STEPS + 4 * (uint32_t)i));
}
EXE_LOADER(sfx_tables_load)
''' % dict(SAMPLES=SAMPLES, SSTRIDE=SSTRIDE, LIST=LIST, STEPS=STEPS)
sys.stdout.write(src)
