/* Generated by tools/gen_sfx_tables.py from the layout of RFIRE.BIN. Do not edit.
   Sample table 0x43e550, sound-event table 0x43e960..0x43edc8, event list 0x43ede0,
   bunker lift sound steps 0x43f278 (docs/architecture.md section 7). Addresses only: the contents are
   read from the user's RFIRE.BIN at start-up (exe.c, sfx_tables_load below). */
#include "sfx.h"
#include "exe.h"
#include <stdio.h>
#include <stdlib.h>

SfxSample sfx_samples[SFX_NSAMPLES];
SfxEvent sfx_events[SFX_NEVENTS];
uint8_t sfx_event_list[SFX_NLIST];
uint8_t sfx_step_events[2];

enum { SAMPLES = 0x43e550, SSTRIDE = 0x1c, LIST = 0x43ede0, STEPS = 0x43f278 };
static const uint32_t callbacks[3] = { 0, 0x42b960, 0x42b9b0 };   /* SFX_CB_NONE, _ENGINE, _ROTOR */

static void fail(const char *what, uint32_t va)
{
    fprintf(stderr, "sfx_tables: unexpected %s at 0x%x in RFIRE.BIN\n", what, va);
    abort();
}

static uint8_t event_index(uint32_t va)
{
    uint32_t k = (va - SFX_EVENT_BASE) / SFX_EVENT_STRIDE;
    if (va < SFX_EVENT_BASE || k >= SFX_NEVENTS || va != SFX_EVENT_BASE + k * SFX_EVENT_STRIDE) fail("event pointer", va);
    return (uint8_t)k;
}

static void sfx_tables_load(void)
{
    for (int i = 0; i < SFX_NSAMPLES; i++) {
        uint32_t a = SAMPLES + SSTRIDE * (uint32_t)i, mk = exe_u32(a + 20);
        int32_t ls = -1, le = -1;
        for (uint32_t k = mk; mk && exe_u32(k); k += 8) {        /* marker list {tag, value}, 0-terminated */
            if (exe_u32(k) == 0x1f) ls = exe_s32(k + 4);
            else if (exe_u32(k) == 0x20) le = exe_s32(k + 4);
        }
        sfx_samples[i] = (SfxSample){ exe_str(exe_u32(a)), exe_u32(a + 4), ls, le };
    }
    for (int i = 0; i < SFX_NEVENTS; i++) {
        uint32_t a = SFX_EVENT_BASE + SFX_EVENT_STRIDE * (uint32_t)i, samp = exe_u32(a + 4), cb = exe_u32(a + 20);
        uint32_t si = (samp - SAMPLES) / SSTRIDE;
        if (samp < SAMPLES || si >= SFX_NSAMPLES || samp != SAMPLES + si * SSTRIDE) fail("sample pointer", a);
        uint8_t c = cb == callbacks[1] ? SFX_CB_ENGINE : cb == callbacks[2] ? SFX_CB_ROTOR : SFX_CB_NONE;
        if (cb != callbacks[c]) fail("callback", a);
        sfx_events[i] = (SfxEvent){ a, exe_str(exe_u32(a)), (uint8_t)si, exe_u8(a + 8), exe_u8(a + 9), exe_u8(a + 10),
                                    exe_u8(a + 11), exe_s32(a + 12), exe_s32(a + 16), c };
    }
    for (int i = 0; i < SFX_NLIST; i++) sfx_event_list[i] = event_index(exe_u32(LIST + 4 * (uint32_t)i));
    for (int i = 0; i < 2; i++) sfx_step_events[i] = event_index(exe_u32(STEPS + 4 * (uint32_t)i));
}
EXE_LOADER(sfx_tables_load)
