/* Generated by tools/gen_world_tables.py. Do not edit.
   RFM tile table (RFIRE.BIN 0x452858) and BNO map-object fields (0x451438, stride 0x38), read from the
   user's RFIRE.BIN at start-up (exe.c). */
#include "world.h"
#include "exe.h"

TileDef tile_table[240];
ObjDef obj_table[OBJ_COUNT];

static void world_tables_load(void)
{
    for (int i = 0; i < 240; i++) {
        uint32_t a = 0x452858 + 4 * (uint32_t)i;
        tile_table[i] = (TileDef){ exe_u8(a), exe_u8(a + 1), exe_u8(a + 2), exe_u8(a + 3) };
    }
    for (int i = 0; i < OBJ_COUNT; i++) {
        uint32_t b = 0x451438 + 0x38 * (uint32_t)i;
        obj_table[i] = (ObjDef){ exe_str(exe_u32(b + 4)), exe_u8(b + 0x10), exe_u8(b + 0x11), exe_u32(b + 0x34) };
    }
}
EXE_LOADER(world_tables_load)
